### PR TITLE
Check, update node label on machine obj prior to drain,termination

### LINKED ISSUE #875: Edge case where Node Deletion is missed if machine 'node' label is not present
**How to categorize this issue?**

/area robustness
/kind bug
/priority 2

**What happened**:

When a `Node` is never associated with its `Machine`. Ie the `machine` object never has the `machine.Labels[v1alpha1.NodeLabelKey]` set after the machine creation, then during the deletion flow, our `Node` object is not deleted.  (Label up-dation can be missed if the machine object update transiently fails)

Then after some time, the dangling `Node` object gets the `NotManagedByMCM` annotation. 

**What you expected to happen**:
`Node` object should always be deleted prior to the instance VM Termination and `Machine` object deletion, even if the association was missed during instance creation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Launch a `Machine` and then remove its `node` label. 
1. Then delete the machine, triggering the delete flow.
1. After machine object is deleted, the corresponding `Node` is still present.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: any
- Others:

### PR DESCRIPTION
**Pull request by elankath**
**What this PR does / why we need it**:

When a Node is never associated with its Machine. Ie the machine object never has the `machine.Labels[v1alpha1.NodeLabelKey]` set after the machine creation, then during the deletion flow, our Node object is not deleted. (Label updation can be missed if the machine object update transiently fails)

Then after some time, the dangling Node object gets the `NotManagedByMCM` annotation.

**Which issue(s) this PR fixes**:
Fixes #875

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fix for edge case of Node object deletion missed during machine termination.
```

### CODE REVIEW

**Comment by elankath** [comment]
Teested fix on GCP (node label is same as machine name for this provider). Removed the `node` label and initiated machine deletion. Node label is now set again prior to drain and deletion. Node deletion successfully occurs even when `node` label is missing.

```
I1226 10:08:31.120914   86315 machine.go:128] reconcileClusterMachine: Start for "shoot--i034796--g1-w1-z1-788d9-hlgnx" with phase:"Terminating", description:"Set machine status to termination. Now, getting VM Status"
I1226 10:08:33.742750   86315 machine_util.go:1685] Updating "node" label on machine "shoot--i034796--g1-w1-z1-788d9-hlgnx" to "shoot--i034796--g1-w1-z1-788d9-hlgnx"
I1226 10:08:33.926901   86315 machine_util.go:1696] Updated "node" label on machine "shoot--i034796--g1-w1-z1-788d9-hlgnx" to "shoot--i034796--g1-w1-z1-788d9-hlgnx
I1226 10:08:41.699711   86315 machine_util.go:1104] Normal delete/drain has been triggerred for machine "shoot--i034796--g1-w1-z1-788d9-hlgnx"
...
I1226 10:11:05.334091   86315 machine_controller.go:131] VM "gce:///OMITTED/shoot--i034796--g1-w1-z1-788d9-hlgnx" for Machine "shoot--i034796--g1-w1-z1-788d9-hlgnx" was terminated succesfully
I1226 10:11:10.681394   86315 machine_util.go:1357] Deleting node "shoot--i034796--g1-w1-z1-788d9-hlgnx" associated with machine "shoot--i034796--g1-w1-z1-788d9-hlgnx"
I1226 10:11:16.055535   86315 machine.go:648] Machine "shoot--i034796--g1-w1-z1-788d9-hlgnx" with providerID "gce:///OMITTED/shoot--i034796--g1-w1-z1-788d9-hlgnx" and nodeName "shoot--i034796--g1-w1-z1-788d9-hlgnx" deleted successfully

```

**Comment by elankath** [comment]
Teested fix on AWS (node label is diff from machine name for this provider). Removed the node label and initiated machine deletion. Node label is now set again prior to drain and deletion. Node deletion successfully occurs even when node label is missing.

```
I1226 10:37:06.233292   90959 machine_util.go:1685] Updating "node" label on machine "shoot--i034796--aw3-a-z1-9cc57-q6qbl" to "ip-10-180-29-167.eu-west-1.compute.internal"
I1226 10:37:06.405762   90959 machine_util.go:1696] Updated "node" label on machine "shoot--i034796--aw3-a-z1-9cc57-q6qbl" to "ip-10-180-29-167.eu-west-1.compute.internal"
I1226 10:37:55.994989   90959 core.go:285] Machine deletion request has been recieved for "shoot--i034796--aw3-a-z1-9cc57-q6qbl"
I1226 10:37:56.382539   90959 core.go:311] VM "aws:///eu-west-1/i-078071299a1bce4ca" for Machine "shoot--i034796--aw3-a-z1-9cc57-q6qbl" was terminated successfully
I1226 10:38:01.724111   90959 machine_util.go:1357] Deleting node "ip-10-180-29-167.eu-west-1.compute.internal" associated with machine "shoot--i034796--aw3-a-z1-9cc57-q6qbl"
I1226 10:38:01.724126   90959 machine_util.go:1365] Deletion of Node Object "ip-10-180-29-167.eu-west-1.compute.internal" is successful. Initiate machine object finalizer removal
I1226 10:38:07.079213   90959 machine.go:648] Machine "shoot--i034796--aw3-a-z1-9cc57-q6qbl" with providerID "aws:///eu-west-1/i-078071299a1bce4ca" and nodeName "ip-10-180-29-167.eu-west-1.compute.internal" deleted successfully
```

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 1]
```diff
@@ -1666,3 +1680,19 @@ func getNodeName(machine *v1alpha1.Machine) string {
 func getMachineDeploymentName(machine *v1alpha1.Machine) string {
 	return machine.Labels["name"]
 }
+
+func (c *controller) updateMachineNodeLabel(ctx context.Context, machine *v1alpha1.Machine, nodeName string) error {
+	klog.V(2).Infof("Updating %q label on machine %q to %q", v1alpha1.NodeLabelKey, machine.Name, nodeName)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1685]: could you print this log on the caller side

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 2]
```diff
@@ -1344,20 +1354,24 @@ func (c *controller) deleteNodeObject(ctx context.Context, machine *v1alpha1.Mac
...
 			state = v1alpha1.MachineStateProcessing
-
 			err = fmt.Errorf("Machine deletion in process. Deletion of node object was successful")
 		} else {
 			description = fmt.Sprintf("No node object found for %q, continuing deletion flow. %s", nodeName, machineutils.InitiateFinalizerRemoval)
+			klog.Warning(description)
 			state = v1alpha1.MachineStateProcessing
 		}
 	} else {
+		klog.Errorf("Label %q not present on machine %q. Cannot delete associated Node", v1alpha1.NodeLabelKey, machine.Name)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1374]: there could be two conclusion if we enter else
* either label not placed, 
* or node obj is actually not present

I think the log should state both, also the below lines of log and err message should be updated accordingly then

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
some log changes requested

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 1 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go:1685]: Ok, I can make this change, but why ? I mean it makes sense to have it on callee side right.

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 2 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: done

**Review by himanshu-kun — APPROVED** [review]
/lgtm
