### PR TITLE
Check and remove PreferNoSchedule taint from nodes after rolling update

### LINKED ISSUE #989: prefer-no-schedule taint sticks forever if oldMS --> newMS --> oldMS
**How to categorize this issue?**
/area robustness
/kind bug
/priority 3

**What happened**:
a `machineSet` keeps the taint `prefer-no-schedule` forever

**What you expected to happen**:
the taint is removed

**How to reproduce it (as minimally and precisely as possible)**:
have a machienset with rolling update strategy. have a worker definition like so

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: ubuntu
            version: 22.0.4
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```

change the worker image

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: flatcar
            version: 9999.9.9
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```

Wait for the new machineset to be created. 
Change the worker definition back to what it was before:

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: ubuntu
            version: 22.0.4
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```
The "new" machineset will be deleted, the old one will be kept, but tainted, resulting in the machines to be tainted.

**Environment**:

:
- Others:
machine-controller-manager:v0.53.0

### PR DESCRIPTION
**Pull request by aaronfern**
**What this PR does / why we need it**:
We sometimes have a case where the `PreferNoSchedule` taint can remain indefinitely on nodes if we backtrack on a rolling update
This PR adds a check to remove this taint from nodes after a rolling update is complete

**Which issue(s) this PR fixes**:
Fixes #989 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/controller/deployment_rolling.go [hunk 1]
```diff
@@ -115,6 +115,19 @@ func (dc *controller) rolloutRolling(ctx context.Context, d *v1alpha1.MachineDep
...
+		if err = dc.removeTaintNodesBackingMachineSet(
+			ctx,
+			newIS,
+			&v1.Taint{
+				Key:    PreferNoScheduleKey,
+				Value:  "True",
+				Effect: "PreferNoSchedule",
+			},
+		); err != nil {
+			klog.Warningf("Failed to remove taint %s from all nodes. Error: %s", PreferNoScheduleKey, err)
```
Comment (r4mek) [inline pkg/controller/deployment_rolling.go]: Maybe we can quickly requeue the MachineDeployment in case taint removal fails.

File: pkg/controller/deployment_rolling.go [hunk 2]
```diff
@@ -115,6 +115,19 @@ func (dc *controller) rolloutRolling(ctx context.Context, d *v1alpha1.MachineDep
 				return err
 			}
 		}
+		// This check is needed because sometimes we can backtrack on a deployment, and this taint can stick
+		// See https://github.com/gardener/machine-controller-manager/issues/989 for more details
+		if err = dc.removeTaintNodesBackingMachineSet(
```
Comment (gagan16k) [inline pkg/controller/deployment_rolling.go]: Currently, this function prints logs for all available `MachineSet` during every reconcile
```
I1209 16:50:22.138565   29468 deployment.go:461] Processing the machinedeployment "shoot--i765230--demo-worker-cpu-z2" (with replicas 0)
W1209 16:50:22.138972   29468 deployment_rollback.go:148] No taint exists on machineSet: shoot--i765230--demo-worker-cpu-z2-6fb59. Hence not removing.
I1209 16:50:22.255380   29468 deployment.go:461] Processing the machinedeployment "shoot--i765230--demo-worker-cpu-z3" (with replicas 0)
W1209 16:50:22.255777   29468 deployment_rollback.go:148] No taint exists on machineSet: shoot--i765230--demo-worker-cpu-z3-76b86. Hence not removing.
```
The warning logs might not be necessary for every reconcile, so a check if the annotation exists before calling `removeTaintNodesBackingMachineSet` could be done.

Comment (aaronfern) [reply pkg/controller/deployment_rolling.go]: Updated to avoid unnecessary logs

File: pkg/controller/deployment_rolling.go (hunk 1 above)
Comment (aaronfern) [reply pkg/controller/deployment_rolling.go]: Made the requested changed as part of https://github.com/gardener/machine-controller-manager/pull/1001/commits/8c8363438eed89352604487e8cee3ca77f851ddd

**Review by r4mek — APPROVED** [review]

**Review by gagan16k — APPROVED** [review]
