### PR TITLE
Unnecessary machine creation and immediate deletion fix

### LINKED ISSUE #1068: MCM creates a Machine and immediately deletes it
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority 1

**What happened**:
There is an edge case where if CA sends a scale-down request to `MCM`, `MachineDeployment.Replicas` and `MachineSet.Replicas` can be out-of-sync, which causes `MachineSet` to create an unnecessary Machine which immediately gets deleted after `MachineDeployment.Replicas` and `MachineSet.Replicas` get back in sync.

**What you expected to happen**:
No unnecessary `Machine` should be created by `MachineSet` in such cases.

**How to reproduce it (as minimally and precisely as possible)**:
This is a timing issue where reconciliation of `MachineSet` starts before `MachineDeployment` is able to set correct `MachineSet.Replicas` but `MachineDeployment` has already marked the `Machine` with annotation to delete it. Now, in machineSet reconciliation, `Machine` gets deleted but `MachineSet.Replicas` still has stale value. Hence, an unnecessary machine is created and gets marked for deletion instantly.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by r4mek**
**What this PR does / why we need it**:
This PR contains fix for the issue #1068, where MCM was creating a machine and immediately deletes it. This happened because of timing issue in MCM. Refer the issue for further details.

Summarizing the approach:
This PR solves the issue by first letting `MachineSet` controller take scaling decisions based on what view it has of the cluster. And the stale machine termination is done at the end. We know that in the next reconciliation, `MachineSet` controller will also observe the deletion of `staleMachines` done in the previous reconciliation. Hence, `MachineSet` controller at all times will atmost lag behind `MachineDeployment` controller by 1 reconciliation.

**Which issue(s) this PR fixes**:
Fixes #1068 

**Special notes for your reviewer**:

**Release note**:

```other operator
Fix machines termination in machine set replica management to avoid needless scale-up of machines because of stale replica count.
```

### CODE REVIEW

**Comment by r4mek** [comment]
# Manual Testing to mock the error scenario

<details>
<summary>Testing code added</summary>

```
func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1.Machine, machineSet *v1alpha1.MachineSet) error {
	machineSetKey, err := KeyFunc(machineSet)
        if err != nil {
		utilruntime.HandleError(fmt.Errorf("Couldn't get key for %v %#v: %v", machineSet.Kind, machineSet, err))
		return nil
	}

	// Testing the timing issue.
	mcd := c.getMachineDeploymentsForMachineSet(machineSet)
	if mcd[0].Spec.Replicas == 5 {
		mcdCopy := mcd[0].DeepCopy()
		mcdCopy.Spec.Replicas = 4
		mcdCopy.Annotations[machineutils.TriggerDeletionByMCM] = allMachines[0].Name
		_, err = c.controlMachineClient.MachineDeployments(c.namespace).Update(ctx, mcdCopy, metav1.UpdateOptions{})
	}
        ...
}
```

</details>

## Logs
<details>
<summary> Previous logs </summary>

```
I0216 12:54:51.165641   47769 deployment.go:462] Processing the machinedeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" (with replicas 5)           <---- Original MachineDeployment ReplicaCount
I0216 12:54:51.165883   47769 machineset.go:540] Processing the machineset "shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f" with replicas 5 associated with machine class: "shoot--i759930--mcm-test-aws-worker-wvzit-z1-ea1f0"           <---- MachineSet ReplicaCount is 5
I0216 12:54:52.603338   47769 deployment.go:462] Processing the machinedeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" (with replicas 4)            <---- MachineDeployment ReplicaCount changed to 4
I0216 12:54:52.867647   47769 deployment.go:678] Machine "shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f-g9glh" of MachineDeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" marked with MachinePriority=1 annotation successfully           <---- Machine being marked for deletion
...
I0216 12:54:53.123005   47769 machineset.go:364] Deleting stale machines [shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f-g9glh]                <---- Marked Machine is being deleted
...
I0216 12:54:53.908718   47769 machineset.go:419] Too few replicas for MachineSet shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f, need 5, creating 1      <---- MachineSet has stale ReplicaCount value and decides to create a Machine
...
I0216 12:54:54.579871   47769 machineset.go:467] Too many replicas for  shoot--i759930--mcm-test-aws/shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f, need 4, deleting 1               <---- MachineSet ReplicaCount is in sync with MachineDeployment ReplicaCount. Hence, deleting the previously created Machine
...
```

</details>

<details>
<summary> Code-fix logs </summary>

```
I0216 10:34:05.210045   42527 deployment.go:462] Processing the machinedeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" (with replicas 5)             <---- Original MachineDeployment ReplicaCount
I0216 10:34:05.210509   42527 machineset.go:516] Processing the machineset "shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f" with replicas 5 associated with machine class: "shoot--i759930--mcm-test-aws-worker-wvzit-z1-ea1f0".                   <---- MachineSet ReplicaCount is 5
I0216 10:34:06.685749   42527 deployment.go:462] Processing the machinedeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" (with replicas 4)               <---- MachineDeployment ReplicaCount changed to 4
...
I0216 10:34:06.949244   42527 deployment.go:678] Machine "shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f-282tq" of MachineDeployment "shoot--i759930--mcm-test-aws-worker-wvzit-z1" marked with MachinePriority=1 annotation successfully                     <---- Machine is being marked for deletion
...
I0216 10:34:08.297444   42527 machineset.go:422] Too many replicas for  shoot--i759930--mcm-test-aws/shoot--i759930--mcm-test-aws-worker-wvzit-z1-5954f, need 4, deleting 1                   <---- Marked Machine is being deleted
...
```

</details>

File: pkg/controller/machineset.go [hunk 1]
```diff
@@ -335,52 +335,19 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
 		return nil
 	}
 
-	var activeMachines, staleMachines, machinesWithUpdateSuccessfulLabel []*v1alpha1.Machine
+	allMachinesDiff := len(allMachines) - int(machineSet.Spec.Replicas)
```
Comment (takoverflow) [inline pkg/controller/machineset.go]: Consider moving `allMachinesDiff` next to `machinesWithoutUpdateSuccessfulLabelDiff`

File: pkg/controller/machineset.go [hunk 2]
```diff
@@ -335,52 +335,19 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
 		}
-		diff += len(machinesWithUpdateSuccessfulLabel)
 	}
+	machinesWithoutUpdateSuccessfulLabelDiff := len(machinesWithoutUpdateSuccessfulLabel) - int(machineSet.Spec.Replicas)
 
-	klog.V(4).Infof("Difference between current active replicas and desired replicas - %d", diff)
-
-	if diff < 0 {
+	// During in-place updates, ScaleUps are disabled in the oldMachineSet and
+	// in newMachineSet, its ReplicaCount would never increase before a machine from oldMahineSet is moved.
```
Comment (takoverflow) [inline pkg/controller/machineset.go]:
```suggestion
	// in newMachineSet, its ReplicaCount would never increase before a machine from oldMachineSet is moved.
```

Is this guaranteed? Because the earlier fix had a comment saying
> 	// If the MachineSet is scaled up first and the "update successful" label is removed later, this controller might
	// incorrectly assume that additional machines need to be created, as it ignores machines with the "update successful" label.

Is this not a concern because the assumption is that if the machine has the label, then its implied that its owner ref has been switched to the new machineSet, hence it would anyways be considered when looking at `allMachines` for the new machineSet and hence would not be a problem?

File: pkg/controller/machineset.go [hunk 3]
```diff
@@ -443,22 +410,26 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
-	} else if diff > 0 {
-		if diff > BurstReplicas {
-			diff = BurstReplicas
-		}
-		klog.V(2).Infof("Too many replicas for %v %s/%s, need %d, deleting %d", machineSet.Kind, machineSet.Namespace, machineSet.Name, (machineSet.Spec.Replicas), diff)
-
-		logMachinesWithPriority1(activeMachines)
-		machinesToDelete := getMachinesToDelete(activeMachines, diff)
+	} else if machinesWithoutUpdateSuccessfulLabelDiff > 0 {
+		// During in-place updates, in the newMachineSet, it can happen that a machine has come from the oldMachineSet
```
Comment (takoverflow) [inline pkg/controller/machineset.go:422]: This comment should be added at the place where the diff is defined. Since it acts as motivation for computing this additional diff in the first place. WDYT?

File: pkg/controller/machineset.go [hunk 4]
```diff
@@ -478,6 +449,26 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
 		}
 	}
 
+	var staleMachines []*v1alpha1.Machine
+	for _, m := range machinesWithoutUpdateSuccessfulLabel {
+		// Skip machines that are in the process of being updated.
+		if m.Labels[v1alpha1.LabelKeyNodeUpdateResult] == v1alpha1.LabelValueNodeUpdateSuccessful {
```
Comment (takoverflow) [inline pkg/controller/machineset.go]: What is the point of performing this check for `machinesWithoutUpdateSuccessfulLabel`?

File: pkg/controller/machineset.go (hunk 2 above)
Comment (r4mek) [reply pkg/controller/machineset.go]: Yes

File: pkg/controller/machineset.go (hunk 4 above)
Comment (r4mek) [reply pkg/controller/machineset.go]: Yes. This can be removed.

File: pkg/controller/machineset.go (hunk 3 above)
Comment (r4mek) [reply pkg/controller/machineset.go:422]: The comment was to explain why we have the else if condition as `machinesWithoutUpdateSuccessfulLabelDiff > 0` but if needed, can be moved above as well.

**Comment by r4mek** [comment]
Done.

**Review by takoverflow — APPROVED** [review]
