### PR TITLE
 Fix Rotation of log files in IT

### LINKED ISSUE #853: Enhance pipeline setup for IT to adapt to gardener environment changes
**How to categorize this issue?**

/area dev-productivity
/kind enhancement
/priority 1

**What would you like to be added**:

Enhance the following in current pipeline setup for mcm-provider IT

with @rishabh-11 
- [x] Log file renaming should be fixed (https://github.com/gardener/machine-controller-manager/pull/864)
- [x] Remove Dependence on kubeconfig for figuring out if control cluster is seed (https://github.com/gardener/machine-controller-manager/pull/869)

with @himanshu-kun 

*non-pipeline changes:*
- [ ] Remove old IT code from MCM repo (@piyuagr)

*pipeline changes:*
@himanshu-kun 
- [ ] Create a service account in mcm-ci with admin (Will generate a kubeconfig in the project namespace) (One time setup) 
- [ ] Security requirement: Internal job needed to rotate the token for the kubeconfig associated to SA. The token expires every 90 days (default and max) . More info here -> https:// pages. github. tools. sap/kubernetes/gardener/community/mail /2022/000957/.   [Remove interim spaces to make the link]
- [ ] should we create another service account for userData refreshing, or use existing account of any other developer.

@piyuagr 
- [ ] Use the kubeconfig to [generate admin kubeconfig](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsadminkubeconfig-subresource) for *-oot-control and *-oot-target clusters (This step will need to be done everytime the IT is run in pipeline)
- [ ] Turn `*-oot-control` clusters Worker less to save costs (we can remove *-oot-control also)
  - [ ] See if control cluster = target cluster is working fine in IT

@sssash18 
- [ ] Create a cluster role and binding which gives access to secrets in garden-core namespace. Associate binding with service account. 

**Why is this needed**:

Recently security hardening has been done for gardener deployment where the kubeconfigs have turned non-static (expires after 24h max). This has created problems for our pipeline IT , given the way we currently set them up. Through this issue we plan to make minimal changes to get the IT up and running.
Some other changes (not-urgent-for-now) are tracked in https://github.com/gardener/machine-controller-manager/issues/787

### PR DESCRIPTION
**Pull request by piyuagr**
**What this PR does / why we need it**:
This PR fixes the rotation of Log files issue on multiple runs of Integration tests. 

**Which issue(s) this PR fixes**:
Fixes:- Part of #853 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: pkg/test/integration/common/framework.go [hunk 1]
```diff
@@ -686,18 +687,31 @@ func (c *IntegrationTestFramework) setupMachineClass() error {
...
+			noOfFiles++
+			temp = fileName + "." + strconv.Itoa(noOfFiles)
+			_, err = os.Stat(temp)
+		}
+		// Renaming all log files having last characters as ".x" where x >=1
+		for i := noOfFiles - 1; i > 0; i-- {
 			f := fmt.Sprintf("%s.%d", fileName, i)
 			fNew := fmt.Sprintf("%s.%d", fileName, i+1)
 			if err := os.Rename(f, fNew); err != nil {
+				fmt.Println(i, " ")
```
Comment (rishabh-11) [inline pkg/test/integration/common/framework.go:704]:
```suggestion
```

File: pkg/test/integration/common/framework.go [hunk 2]
```diff
@@ -686,18 +687,31 @@ func (c *IntegrationTestFramework) setupMachineClass() error {
...
+		noOfFiles := 1
+		temp := fileName + "." + strconv.Itoa(noOfFiles)
+		_, err := os.Stat(temp)
+		// Finding the total number of log files
+		for err == nil {
+			noOfFiles++
+			temp = fileName + "." + strconv.Itoa(noOfFiles)
+			_, err = os.Stat(temp)
+		}
+		// Renaming all log files having last characters as ".x" where x >=1
```
Comment (rishabh-11) [inline pkg/test/integration/common/framework.go:699]:
```suggestion
```

File: pkg/test/integration/common/framework.go [hunk 3]
```diff
@@ -686,18 +687,31 @@ func (c *IntegrationTestFramework) setupMachineClass() error {
 // If the file exists already then it renames it so that a new file can be created
 func rotateLogFile(fileName string) (*os.File, error) {
 	if _, err := os.Stat(fileName); err == nil { // !strings.Contains(err.Error(), "no such file or directory") {
-		for i := 9; i > 0; i-- {
+		noOfFiles := 1
+		temp := fileName + "." + strconv.Itoa(noOfFiles)
+		_, err := os.Stat(temp)
+		// Finding the total number of log files
```
Comment (rishabh-11) [inline pkg/test/integration/common/framework.go:693]:
```suggestion
		// Finding the log files ending with ".x" where x >= 1 and renaming them
```

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
Thanks for the PR. Minor changes needed

File: pkg/test/integration/common/framework.go (hunk 3 above)
Comment (piyuagr) [reply pkg/test/integration/common/framework.go]: Done

File: pkg/test/integration/common/framework.go (hunk 2 above)
Comment (piyuagr) [reply pkg/test/integration/common/framework.go]: Removed

File: pkg/test/integration/common/framework.go (hunk 1 above)
Comment (piyuagr) [reply pkg/test/integration/common/framework.go]: Removed

**Review by rishabh-11 — APPROVED** [review]
/lgtm
