### PR TITLE
Machines are reconciled only when MachineClasses have valid finalizers

### LINKED ISSUE #560: Add finalizers on machineClasses only when machines referring it
**What happened**:
Currently, MCM adds finalizers on machineClasses unless the deletionTimestamp is set. And this adds finalizers to machineClass that probably aren't used. 

**What you expected to happen**:
MachineClasses to have finalizers only when machines backing them are present.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
This would also mean that the machine reconciliation for a machine object should not be started unless there is a machineClass finalizers set by MCM. Because in the past we had made this change however, the race conditions lead to machines without machineClass objects backing it. 

**Environment**:
/area ops-productivity
/size xs
/exp beginner

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**What this PR does / why we need it**:
Implements MachineClasses to have finalizers only when machines backing them are present.

**Which issue(s) this PR fixes**:
Fixes #560 

**Special notes for your reviewer**:
The change has been introduced for OOT MCM common library. If there is a need then it shall be introduced in In-Tree too.

**Release note**:

```feature operator
Finalizers will be added to the MachineClass which is used by at least one machine. Machines whose backing MachineClass does not have finalizers shall not be reconciled.
```

### CODE REVIEW

**Review by prashanth26 — CHANGES_REQUESTED** [review]
Thanks for this PR. 

The unit tests probably need refactoring as well.

**Comment by AxiomSamarth** [comment]
Unit tests refactored and a new relevant test added too! 😄

File: pkg/util/provider/machinecontroller/machine.go [hunk 1]
```diff
@@ -134,6 +134,8 @@ func (c *controller) reconcileClusterMachine(machine *v1alpha1.Machine) (machine
 		return machineutils.LongRetry, err
 	}
 
+	// Validate MachineClass
+	klog.Infof("Validating Machine Class %s backing machine %s", machine.Spec.Class.Name, machine.Name)
```
Comment (prashanth26) [inline pkg/util/provider/machinecontroller/machine.go:138]: Do we need this?

File: kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml [hunk 2]
```diff
@@ -59,9 +59,6 @@ spec:
             object represents. Servers may infer this from the endpoint the client
             submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
           type: string
-        metadata:
```
Comment (prashanth26) [inline kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml:62]: I hope this change is intensional?

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 3]
```diff
@@ -123,6 +123,18 @@ func (c *controller) ValidateMachineClass(classSpec *v1alpha1.ClassSpec) (*v1alp
...
+	clone := machineClass.DeepCopy()
+
+	if finalizers := sets.NewString(clone.Finalizers...); !finalizers.Has(MCMFinalizerName) {
+		klog.Errorf("The machine class %s has no finalizers set. So not reconciling the machine.", machineClass.Name)
+		err = c.reconcileClusterMachineClassKey(machineClass.Name)
+		if err != nil {
+			klog.Errorf("Machine Class %q: Error occured while reconciling: %v", machineClass.Name, err)
+			return machineClass, secretData, retry, err
+		}
+		return machineClass, secretData, retry, err
```
Comment (prashanth26) [inline pkg/util/provider/machinecontroller/machine_util.go:135]: The controller way of doing this is by [re-enqueing the object to the queue](https://github.com/gardener/machine-controller-manager/blob/master/pkg/util/provider/machinecontroller/machineclass.go#L87) and returning an error here.

**Review by prashanth26 — CHANGES_REQUESTED** [review]
Apologies for the super late review. Better late than never 😄

File: kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml (hunk 2 above)
Comment (AxiomSamarth) [reply kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml:62]: Yes. Prashanth. It is the solution for the issue - https://github.com/gardener/machine-controller-manager/pull/551

File: pkg/util/provider/machinecontroller/machine.go (hunk 1 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine.go:138]: Yeah, it does not really make a difference. I will remove it

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 3 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine_util.go:135]: Okay

File: kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml (hunk 2 above)
Comment (prashanth26) [reply kubernetes/crds/machine.sapcloud.io_machinedeployments.yaml:62]: Okay. In future, let's try to move minor independent fixes into it's on PRs. Just to keep it followable via commits.

**Comment by prashanth26** [comment]
The commits seem to be messed up. Can you please fix it?

**Review by prashanth26 — APPROVED** [review]
/lgtm

File: pkg/util/provider/machinecontroller/machine_test.go [hunk 4]
```diff
@@ -241,6 +241,13 @@ var _ = Describe("machine", func() {
 		objMeta := &metav1.ObjectMeta{
 			GenerateName: "class",
 			Namespace:    testNamespace,
+			Finalizers:   []string{MCMFinalizerName},
+		}
+
+		objMetaWithoutFinalizer := &metav1.ObjectMeta{
+			GenerateName: "class",
+			Namespace:    testNamespace,
+			Finalizers:   []string{MCMFinalizerName},
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_test.go:250]: I think `Finalizers` field shouldn't be a part of this

File: pkg/util/provider/machinecontroller/machine_test.go [hunk 5]
```diff
@@ -346,6 +362,34 @@ var _ = Describe("machine", func() {
 					err:        false,
 				},
 			}),
+			Entry("machineClass without Finalizer", &data{
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_test.go:365]: are we just trying to show that machineClass which doesn't have finalizer will be marked by finalizer in this Testcase.

File: pkg/util/provider/machinecontroller/machine_test.go [hunk 6]
```diff
@@ -253,6 +260,15 @@ var _ = Describe("machine", func() {
...
 
+				machine1 := &v1alpha1.Machine{
+					ObjectMeta: *newObjectMeta(objMeta, 0),
+					Spec: v1alpha1.MachineSpec{
+						Class: *data.action,
+					},
+				}
+
+				machineObjects = append(machineObjects, machine1)
+
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_test.go:271]: I see this `machine1` object being appended in `machineObjects` list but I don't see it being used in any testcases?

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
Thanks for giving me this opportunity to review. I think I have my doubts at some places, would be really helpful if you could clear them @AxiomSamarth . I won't be able to respond today as I am on leave.
Pls proceed with merging the PR if you think you have answered my doubts :)

File: pkg/util/provider/machinecontroller/machine_test.go (hunk 4 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine_test.go]: Good catch! Thank you

File: pkg/util/provider/machinecontroller/machine_test.go (hunk 5 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine_test.go:355]: The idea is - if a MachineClass does not have a finaliser then the machineClass should not be reconciled.

File: pkg/util/provider/machinecontroller/machine_test.go (hunk 6 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine_test.go]: You are correct, Himanshu. It is a redundant entry. 

The idea behind creating the machine object was to check that the machineClass gets a finaliser only when there is atleast one machine using it. I have written a different test case in `MachineClass_test.go` now. Again, good catch 😉

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 7]
```diff
@@ -123,6 +124,15 @@ func (c *controller) ValidateMachineClass(classSpec *v1alpha1.ClassSpec) (*v1alp
...
 
+	clone := machineClass.DeepCopy()
+
+	if finalizers := sets.NewString(clone.Finalizers...); !finalizers.Has(MCMFinalizerName) {
+		klog.Errorf("The machine class %s has no finalizers set. So not reconciling the machine.", machineClass.Name)
+		c.machineClassQueue.Add(machineClass.Name)
+		err := errors.New("The machine class %s has no finalizers set. So not reconciling the machine." + machineClass.Name)
+		return nil, nil, retry, err
+	}
+
```
Comment (prashanth26) [inline pkg/util/provider/machinecontroller/machine_util.go:135]:
```suggestion
	if finalizers := sets.NewString(machineClass.Finalizers...); !finalizers.Has(MCMFinalizerName) {
		klog.Errorf("The machine class %s has no finalizers set. So not reconciling the machine.", machineClass.Name)
		err := errors.New("The machine class %s has no finalizers set. So not reconciling the machine." + machineClass.Name)
		c.machineClassQueue.Add(machineClass.Name)
		return nil, nil, retry, err
	}

```
Do we need to clone this machineClass object?

**Review by prashanth26 — COMMENTED** [review]
One final minor comment

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 7 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/machine_util.go]: Changes made in the latest commit.

**Comment by prashanth26** [comment]
/title Machines are reconciled only when MachineClasses have valid finalizers
