### PR TITLE
Fix panic in AWS driver if AMI not found.

### LINKED ISSUE #278: MCM stumbles over invalid AMI ID (AWS)
**What happened**:

I tried to create a cluster which did not come up. I suspect the root cause for this is an invalid/deleted ami image on AWS. 

What I saw is that mcm explodes on this - presumable the missing ami image (this is the log output of the mcm):

```
[...]
W0611 10:55:21.476443       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0611 10:55:21.477765       1 leaderelection.go:187] attempting to acquire leader lease  shoot--core--dm-jeos/machine-controller-manager...
I0611 10:55:21.766983       1 leaderelection.go:196] successfully acquired lease shoot--core--dm-jeos/machine-controller-manager
I0611 10:55:21.767168       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"shoot--core--dm-jeos", Name:"machine-controller-manager", UID:"dbaf8217-8c28-11e9-a125-0a580a3009da", APIVersion:"v1", ResourceVersion:"2857289363", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' machine-controller-manager-67fdd6db6-9t82w became leader
I0611 10:55:22.483820       1 controllermanager.go:273] Starting shared informers
I0611 10:55:22.884020       1 controller.go:475] Starting machine-controller-manager
I0611 10:55:22.975325       1 machine.go:339] Creating machine "shoot--core--dm-jeos-worker-tkg6a-z1-6b8695c5b5-thrxr", please wait!
I0611 10:55:22.975325       1 machine.go:339] Creating machine "shoot--core--dm-jeos-worker-tkg6a-z1-6b8695c5b5-zskmj", please wait!
E0611 10:55:23.391236       1 runtime.go:66] Observed a panic: "index out of range" (runtime error: index out of range)
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:44
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/driver/driver_aws.go:74
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:341
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:192
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:108
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:535
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:552
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:514
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 600 [running]:
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1b814e0, 0x3ac71a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/gardener/machine-controller-manager/pkg/driver.(*AWSDriver).Create(0xc0007fc340, 0x0, 0x1f016b1, 0x21, 0xc001483960, 0x1, 0x1)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/driver/driver_aws.go:74 +0x1779
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).machineCreate(0xc000bb4000, 0xc00062d180, 0x2214b20, 0xc0007fc340, 0x21cdca0, 0xc001492090)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:341 +0xbc
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).reconcileClusterMachine(0xc000bb4000, 0xc00062d180, 0x0, 0x0)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:192 +0x6c2
github.com/gardener/machine-controller-manager/pkg/controller.(*controller).reconcileClusterMachineKey(0xc000bb4000, 0xc000fccaf0, 0x4a, 0x18, 0xc0013f8d10)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/machine.go:108 +0x23f
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1.1(0x223d960, 0xc0007c7140, 0xc00043c6f0, 0x458701, 0xf, 0x1ee63fd, 0xe, 0x203000)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:535 +0xe3
github.com/gardener/machine-controller-manager/pkg/controller.worker.func1()
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:552 +0x8d
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007fc040)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007fc040, 0x3b9aca00, 0x0, 0x1, 0x0)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/gardener/machine-controller-manager/pkg/controller.createWorker.func1(0x223d960, 0xc0007c7140, 0x1ee63fd, 0xe, 0xf, 0x1, 0xc00043c6f0, 0x0, 0xc0006f4040)
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:514 +0xa0
created by github.com/gardener/machine-controller-manager/pkg/controller.createWorker
	/tmp/build/80754af9/git-gardener_machine-controller-manager-master_master/tmp/src/github.com/gardener/machine-controller-manager/pkg/controller/controller.go:513 +0xbe
```

**What you expected to happen**:

MCM does not explode but handles the problem with an error message.

**How to reproduce it (as minimally and precisely as possible)**:

There is a```dm-jeos``` cluster in the ```core``` project in canary which currently suffers the problem with the non existing image and he mcm dump.

**Anything else we need to know?**:

The image id will probably get fixed tomorrow.

### PR DESCRIPTION
**Pull request by amshuman-kr**
**What this PR does / why we need it**:
Avoid panic in the AWS driver if invalid AMI is supplied.

**Which issue(s) this PR fixes**:
Fixes #278 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fix panic in AWS driver if AMI not found.
```

### CODE REVIEW

File: pkg/driver/driver_aws.go [hunk 1]
```diff
@@ -70,6 +70,10 @@ func (d *AWSDriver) Create() (string, string, error) {
 	}
 	metrics.APIRequestCount.With(prometheus.Labels{"provider": "aws", "service": "ecs"}).Inc()
 
+	if len(output.Images) < 1 {
```
Comment (hardikdr) [inline pkg/driver/driver_aws.go]: Wondering if makes sense to add checks for `Spec.BlockDevices` and `Spec.NetworkInterfaces` as well.

Afaik we tackle these cases in the validation package but double-check here should be fine.
- https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/validation/awsmachineclass.go#L70 
Not sure though how it still panicked.

Comment (amshuman-kr) [reply pkg/driver/driver_aws.go]: `BlockDevices` and `NetworkInterfaces` are in `spec`. For them, validation is enough.

The AMI check is for driver API call response, hence this check. I could not see any other unchecked indexing of arrays/slices in the `Create` call at least.

**Comment by amshuman-kr** [comment]
In the out-of-tree drivers' (for all) unit tests, we should cover this case.

File: pkg/driver/driver_aws.go (hunk 1 above)
Comment (ggaurav10) [reply pkg/driver/driver_aws.go]: i don't believe it fixes #278. New comment: https://github.com/gardener/machine-controller-manager/issues/278#issuecomment-501674918
Also, if the image is not found, it should have been caught here:
https://github.com/gardener/machine-controller-manager/pull/279/files#diff-9e1fc8d4d5952f923e158f3a60af4036R67

Comment (ggaurav10) [reply pkg/driver/driver_aws.go]: The error returned would be `InvalidAMIID.NotFound` according to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors

**Comment by amshuman-kr** [comment]
I am not sure why the CI test failed. I do not have the access rights to check the build logs. The build and unit-tests succeeded locally.

**Comment by hardikdr** [comment]
The control-ci cluster could have been hibernated. re-running.

File: pkg/driver/driver_aws.go (hunk 1 above)
Comment (amshuman-kr) [reply pkg/driver/driver_aws.go]: Ideally yes. But we have seen AWS SDK issues (especially, related to error codes) with the CCM as well recently with stale nodes not being cleaned up.

Besides, the logs reported in #278 are about `index out of range` on this exact line. And the image clearly doesn't exist. Not checking length before `output.Images[0]` is not ideal either even if the error codes are consistent.

Comment (amshuman-kr) [reply pkg/driver/driver_aws.go]: > Not sure though how it still panicked.

@hardikdr This is not the case where `spec.API` is `nil`. It is not `nil` but it does not exist. This case cannot be checked during validation at all.

Also, the SDK or the EC2 API seems to be misbehaving as @ggaurav10 pointed out.

Comment (ggaurav10) [reply pkg/driver/driver_aws.go]: According to https://github.com/gardener/machine-controller-manager/issues/278#issuecomment-501674918 the AMI exists. Still panic is seen. With this PR, MCM would not panic, and return "Image not found".

Comment (amshuman-kr) [reply pkg/driver/driver_aws.go]: > The error returned would be InvalidAMIID.NotFound according to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors

I don't think this is entirely correct, now that I think about it. The CommonErrors listing is a list of all common errors. The documentation does not where which API returns which error for what reason?

It makes sense for `RunInstances` to return `InvalidAMIID.NotFound`. It does not make any sense for `DescribeImages` to return `InvalidAMIID.NotFound`. No?

Comment (ggaurav10) [reply pkg/driver/driver_aws.go]: According to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html
`DescribeImages` should also return common errors if I understood it correct.

Comment (ggaurav10) [reply pkg/driver/driver_aws.go]: Tried the scenario with random AMI ID that doesn't exist. Following error is returned by `DescribeImages`:
 ```
InvalidAMIID.NotFound: The image id '[ami-012abdf0d2781f0b5]' does not exist
	status code: 400, request id: fa359937-1b4e-4596-a301-3d3932d5f565
```
The returned `output` struct is empty.
Having said that, there is no harm in still checking of the array `Images` has zero length or not. :)

**Comment by marwinski** [comment]
An addition: it would be really useful if the MCM could write the unsuccessful ami-id into the log. The cluster that was ok is not working anymore (reason is that MCM runs into the problem fixed with this PR). The id apparently did not change (or did it) but maybe the image has been removed.
