### PR TITLE
Diagnostics Logs for MCM

### LINKED ISSUE #905: Add diagnostic logs for MCM
**How to categorize this issue?**

/area logging
/kind enhancement
/priority 3

**What would you like to be added**:
1. Log when machine phase changes to `Failed`
1. Log machines that are marked to be deleted by CA.

**Why is this needed**:
For further information when debugging issues.

### PR DESCRIPTION
**Pull request by elankath**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #905

**Special notes for your reviewer**:

**Release note**:

```other developer
NONE
```

### CODE REVIEW

File: pkg/controller/machineset.go [hunk 1]
```diff
@@ -427,7 +427,9 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
 		}
 		klog.V(2).Infof("Too many replicas for %v %s/%s, need %d, deleting %d", machineSet.Kind, machineSet.Namespace, machineSet.Name, (machineSet.Spec.Replicas), diff)
 
+		logMachinesWithPriorityAnnotation(activeMachines)
```
Comment (rishabh-11) [inline pkg/controller/machineset.go:430]: Actually, each machine will have a priority annotation set. Should we just log machines with priority set to `1` instead?

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
one minor comment. rest looks good. thanks for the PR.

File: pkg/controller/machineset.go (hunk 1 above)
Comment (elankath) [reply pkg/controller/machineset.go:430]: Hmm..ok, I thought it might be useful to see if there was something strange/diff about priority. But yes, to avoid overlog we can limit this to p1.

**Review by rishabh-11 — APPROVED** [review]
/lgtm

**Review by rishabh-11 — APPROVED** [review]
/lgtm
