### PR TITLE
Keep `DesiredReplicas` annotation up to date even if no scaling happens

### LINKED ISSUE #815: [Edge case] Stale `deployment.kubernetes.io/desired-replicas` annotation block rollout
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:

A case was seen where there was a single machineSet under the machineDeployment with `deployment.kubernetes.io/desired-replicas` not up-to-date with `machinedeloyment.spec.replicas` , but `machineSet.spec.Replicas ==machineDeployment.spec.replicas`

This led to scaling being detected for this machineDeployment in every reconcile but [`scale`](https://github.com/gardener/machine-controller-manager/blob/7b6f3a000d6e2f3f73b798437ba10b899dedcdc7/pkg/controller/deployment_sync.go#L406-L408) not actually happening.

Later when the consumer triggered a rollout (machineDeployment started referring new machineClass) , the rollout never starts as [rollout logic](https://github.com/gardener/machine-controller-manager/blob/7b6f3a000d6e2f3f73b798437ba10b899dedcdc7/pkg/controller/deployment.go#L541) is called after [scaling](https://github.com/gardener/machine-controller-manager/blob/7b6f3a000d6e2f3f73b798437ba10b899dedcdc7/pkg/controller/deployment.go#L532-L535C1) logic 

**What you expected to happen**:

- `deployment.kubernetes.io/desired-replicas` to re-sync 
- rollout not to get blocked

**How to reproduce it (as minimally and precisely as possible)**:

I am not sure how this situation was reached. Ideally , on any machineSet update , all the machineSets are updated, which should update `deployment.kubernetes.io/desired-replicas` also.

But these set of events could lead to this situation:
image

**Anything else we need to know?**:

**Environment**:
mcm 0.49.0

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by rishabh-11**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #815 

**Special notes for your reviewer**:

**Release note**:

```bugfix user
An edge case where outdated DesiredReplicas annotation blocked a rolling update is fixed.
```

### CODE REVIEW

File: pkg/controller/deployment_sync_test.go [hunk 1]
```diff
@@ -840,6 +841,21 @@ var _ = Describe("deployment_sync", func() {
 					err: false,
 				},
 			}),
+			Entry("if no scaling happened but DesiredReplicas Annotation for the only active machineSet is outdated, it should be updated with the correct value", &data{
```
Comment (himanshu-kun) [inline pkg/controller/deployment_sync_test.go:844]:
```suggestion
			Entry("if no scaling needed but DesiredReplicas Annotation for the only active machineSet is outdated, it should be updated with the correct value", &data{
```

**Review by himanshu-kun — APPROVED** [review]
/lgtm
