### PR TITLE
Set Machine Phase to Terminating & make drain calculations based on deletionTimestamp

### LINKED ISSUE #563: Machines are being force drained
**What happened**:
Machines are being force drained (before drain timeout) instead of a regular drain. This leads to disruption of PDBs and serial PV detachments causing downtimes.

**What you expected to happen**:
Machines to not be force drained before hitting drain timeout. 

**How to reproduce it (as minimally and precisely as possible)**:
Take a cluster with several nodes running smoothly over the default drain timeout period. And now delete the machine backing this node. Force drain is triggered (not always) but in many cases.

**Anything else we need to know**:
- This is most likely a regression due to https://github.com/gardener/machine-controller-manager/pull/492, where machine phase change to terminating state was moved in the code. This caused the drain to consider an old timeStamp leading to force drains. 
- Refer [machineSet deletion](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machineset.go#L641-L662). 

**Environment**:
MCM in-tree v0.34.3. OOT is unaffected by this.

/priority blocker
/kind regression

### PR DESCRIPTION
**Pull request by prashanth26**
**What this PR does / why we need it**:
This PR fixes the race condition that triggers force deletion of machines which are less than drain timeout minutes old. Fixes regressions from #492 . 

**Which issue(s) this PR fixes**:
Fixes #563 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Set Machine Phase to Terminating before draining. 
```
```noteworthy operator
Machine force deletion computation is based on deletionTimestamp instead of LastUpdatedTimestamp. 
```
/invite @guydaichs

### CODE REVIEW

**Comment by prashanth26** [comment]
Open for initial review. 
Please /hold until tests are done.

**Review by guydaichs — APPROVED** [review]
lgtm. thanks for catching this.

**Review by amshuman-kr — COMMENTED** [review]
Why don't we use `deletionTimestamp` here? Using `CurrentStatus.LastUpdateTime` seems flaky.
```go
		timeOut := metav1.Now().Add(-timeOutDuration).Sub(machine.Status.CurrentStatus.LastUpdateTime.Time)
```

**Comment by prashanth26** [comment]
Hi @amshuman-kr ,

I got the same thought lately when I was looking into the issue. But to maintain the original logic, I stuck to this. However, I also think deletionTimeStamp should be more consistent provided the drain logic isn't delayed for some other reason.

**Comment by prashanth26** [comment]
Hi @amshuman-kr ,

I have made this change here - https://github.com/gardener/machine-controller-manager/pull/564/files#diff-d52f3782153512c736878e861c6cafd75dd23f214af3f017eea14de256da458bR658. However, one of the test cacse seems to be failing will fix that and test this change with a running ccluster. In the meanwhile have pushed the changes for you to have look.

**Comment by prashanth26** [comment]
/unhold 
open for review

**Comment by prashanth26** [comment]
/ok-to-test
Tests failed due to rate limiting at docker

**Comment by prashanth26** [comment]
Just ran the MCM locally with and without the fix. Without the fix I am able to reproduce the force drain issue, but with the fix it no longer occurs.

**Review by amshuman-kr — APPROVED** [review]
LGTM

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 1]
```diff
@@ -912,9 +913,7 @@ func (c *controller) drainNode(deleteMachineRequest *driver.DeleteMachineRequest
 	if skipDrain {
 		state = v1alpha1.MachineStateProcessing
 	} else {
-		// Timeout value obtained by subtracting last operation with expected time out period
-		timeOut := metav1.Now().Add(-timeOutDuration).Sub(machine.Status.CurrentStatus.LastUpdateTime.Time)
-		timeOutOccurred = timeOut > 0
+		timeOutOccurred = utiltime.HasTimeOutOccurred(*machine.DeletionTimestamp, timeOutDuration)
```
Comment (hardikdr) [inline pkg/util/provider/machinecontroller/machine_util.go:916]: Nice, thanks for this.

File: pkg/util/time/time_test.go [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+			Entry("Time stamp is one hour ago and period is 90mins", &data{
+				setup: setup{
+					timeStamp: metav1.Time{Time: time.Now().Add(-time.Hour)},
+					period:    90 * time.Minute,
+				},
+				expect: expect{
+					timeOutOccurred: false,
+				},
+			}),
+			Entry("Time stamp is now and peroid is 5mins", &data{
```
Comment (hardikdr) [inline pkg/util/time/time_test.go:66]:
```suggestion
			Entry("Time stamp is now and period is 5mins", &data{
```

**Review by hardikdr — APPROVED** [review]
/lgtm 
Thanks, just a minor typo, ignorable.
