### PR TITLE
Remove NotManagedByMCM when not applicable

### LINKED ISSUE #863: NotManagedByMCM annotation incorrectly added by MCM to Node
**How to categorize this issue?**

/area quality
/kind bug
/priority 2

**What happened**:
Node associated with machines that are managed by the `machine-controller` are being annotated with the `NotManagedByMCM` (`node.machine.sapcloud.io/not-managed-by-mcm="1"`)  annotation.  This can occur plane migration when the Node creation time stamps *predate* the Machine creation time stamps after control plane migration. 

```
kubectl get no -o custom-columns="NAME":.metadata.name,"CREATION":.metadata.creationTimestamp
NAME                                                        CREATION
shoot--di-xm8--dh-tt23jtpe4f2f-static-dynamic-76487-89zwb   2023-08-16T16:42:15Z
shoot--di-xm8--dh-tt23jtpe4f2f-system-57c59-g2f8q           2023-08-16T16:42:17Z
shoot--di-xm8--dh-tt23jtpe4f2f-system-57c59-k9jwh           2023-08-16T16:42:13Z
```
```
k get mc  -o custom-columns="NAME":.metadata.name,"CREATION":.metadata.creationTimestamp
NAME                                                        CREATION
shoot--di-xm8--dh-tt23jtpe4f2f-static-dynamic-76487-89zwb   2023-10-22T05:56:53Z
shoot--di-xm8--dh-tt23jtpe4f2f-system-57c59-g2f8q           2023-10-22T05:56:53Z
shoot--di-xm8--dh-tt23jtpe4f2f-system-57c59-k9jwh           2023-10-22T05:56:53Z
```

**What you expected to happen**:
Ideally, Nodes should not be incorrectly tagged with this annotation. If they have this annotation, the annotation must be removed. A proper fix is described at https://github.com/gardener/machine-controller-manager/issues/774 . Unfortunately, the solution proposed there will take more time since now even gardener code shoot health check is relying on the process of this `NotManagedByMCM` annotation.

*Solution Proposal*
1. In `AnnotateNodesUnmanagedByMCM` (invoked by the safety reconciler),  remove annotation if the `Node` is already associated with `Machine` , yet has this annotation set.
1. Fix needs vendoring and release in all providers.
1. Current default period of safety reconciler job is `30m`. Consider reducing to `5m` after checking that all calls go through informer cache. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
all mcm versions
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all
- Others:

**What you expected to happen**:

### PR DESCRIPTION
**Pull request by elankath**
**What this PR does / why we need it**:

See https://github.com/gardener/machine-controller-manager/issues/863

**Which issue(s) this PR fixes**:
Fixes #863 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Removes `node.machine.sapcloud.io/not-managed-by-mcm` annotation from nodes managed by the MCM.
```
```other operator
The default `machine-safety-orphan-vms-period` has been reduced from 30m to 15m.
```

### CODE REVIEW

File: pkg/util/provider/app/options/options.go [hunk 1]
```diff
@@ -70,7 +71,7 @@ func NewMCServer() *MCServer {
 				MaxEvictRetries:                          drain.DefaultMaxEvictRetries,
 				PvDetachTimeout:                          metav1.Duration{Duration: 2 * time.Minute},
 				PvReattachTimeout:                        metav1.Duration{Duration: 90 * time.Second},
-				MachineSafetyOrphanVMsPeriod:             metav1.Duration{Duration: 30 * time.Minute},
+				MachineSafetyOrphanVMsPeriod:             metav1.Duration{Duration: 15 * time.Minute},
```
Comment (himanshu-kun) [inline pkg/util/provider/app/options/options.go:74]: kindly also mention this in the release notes

File: pkg/util/provider/machinecontroller/machine_safety.go [hunk 2]
```diff
@@ -198,6 +198,19 @@ func (c *controller) AnnotateNodesUnmanagedByMCM(ctx context.Context) (machineut
 					return machineutils.MediumRetry, err
 				}
 			}
+		} else {
+			// FIX: Remove NotManagedByMCM for managed nodes https://github.com/gardener/machine-controller-manager/issues/863
+			_, hasAnnot := node.Annotations[machineutils.NotManagedByMCM]
+			if !hasAnnot {
+				continue
+			}
+			klog.V(3).Infof("Removing NotManagedByMCM annotation from Node %q", node.Name)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_safety.go:207]: also mention the machineName

File: pkg/util/provider/machinecontroller/machine_safety.go [hunk 3]
```diff
@@ -198,6 +198,19 @@ func (c *controller) AnnotateNodesUnmanagedByMCM(ctx context.Context) (machineut
...
+			nodeCopy := node.DeepCopy()
+			delete(nodeCopy.Annotations, machineutils.NotManagedByMCM)
+			_, err := c.targetCoreClient.CoreV1().Nodes().Update(ctx, nodeCopy, metav1.UpdateOptions{})
+			if err != nil {
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_safety.go:211]: why not use `c.updateNodeWithAnnotation()` like used for applying the annotation

File: pkg/util/provider/machinecontroller/machine_safety.go [hunk 4]
```diff
@@ -198,6 +198,19 @@ func (c *controller) AnnotateNodesUnmanagedByMCM(ctx context.Context) (machineut
 					return machineutils.MediumRetry, err
 				}
 			}
+		} else {
+			// FIX: Remove NotManagedByMCM for managed nodes https://github.com/gardener/machine-controller-manager/issues/863
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_safety.go:202]:
```suggestion
```
git blame can be used for this

File: pkg/util/provider/machinecontroller/machine_safety.go [hunk 5]
```diff
@@ -198,6 +198,19 @@ func (c *controller) AnnotateNodesUnmanagedByMCM(ctx context.Context) (machineut
...
+			_, hasAnnot := node.Annotations[machineutils.NotManagedByMCM]
+			if !hasAnnot {
+				continue
+			}
+			klog.V(3).Infof("Removing NotManagedByMCM annotation from Node %q", node.Name)
+			nodeCopy := node.DeepCopy()
+			delete(nodeCopy.Annotations, machineutils.NotManagedByMCM)
+			_, err := c.targetCoreClient.CoreV1().Nodes().Update(ctx, nodeCopy, metav1.UpdateOptions{})
+			if err != nil {
+				klog.Errorf("Failed to remove NotManagedByMCM from Node %q due to: %s", node.Name, err)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_safety.go:212]: could you also add similar error message when applying annotation fails due to Update failure.
Also what retry period will be used on this failure?

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
kindly add a test case for the same

File: pkg/util/provider/machinecontroller/machine_safety.go (hunk 3 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_safety.go:211]: Will need to un-necessarily pass `nil` and that method also has misleading log. It is a method used to add annotations and not remove them.

File: pkg/util/provider/machinecontroller/machine_safety.go (hunk 5 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_safety.go:212]: Just to clarify this. There is already an existing error message in `updateNodeWithAnnotation`  

```
	klog.Errorf("Couldn't patch the node %q , Error: %s", node.Name, err)
```
Do you want me to change this ?

Comment (himanshu-kun) [reply pkg/util/provider/machinecontroller/machine_safety.go]: If the method is not used anywhere other than these annotation, then we can replace it with your version of method..  the idea is to use same method for updating nodes in Annotating/deAnnotating nodes

File: pkg/util/provider/machinecontroller/machine_safety.go (hunk 3 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_safety.go]: Ok, harmonized use of both add/remove to use same method and fixed logging

File: pkg/util/provider/machinecontroller/machine_safety.go (hunk 5 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_safety.go]: Ok, harmonized use of both add/remove to use same method and fixed logging

File: pkg/util/provider/app/options/options.go (hunk 1 above)
Comment (elankath) [reply pkg/util/provider/app/options/options.go:73]: done

**Review by himanshu-kun — APPROVED** [review]
/lgtm
