### PR TITLE
Reduce load on etcd/kube-apiserver on pod eviction

### LINKED ISSUE #703: Reduce load on kube-apiserver / ETCD on pod eviction for termination machines
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:

On rolling nodes of a large cluster with about 100 nodes, the max surge was limited to 10%. The termination of a node was waiting for workload to end. Therefore the rolling took more than 12 hours. This means during this time there have been about 10 machines in state `Terminating`. The machine controller manager tried to evict pods on these nodes with high frequency and produced a lot of load on the kube-apiservers and the ETCD.

image

In this image you see the client out traffic of the ETCD. Between 15:20 and 15:30 we scaled down the machine-controller-manager and the traffic was reduced immediately.

In the logs of the machine-controller-manager we found lots of throttling messages. Here I show only the eviction call for a single pod (name redacted):

```txt
I0412 15:29:36.845890       1 request.go:591] Throttling request took 542.507996ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:29:48.512932       1 request.go:591] Throttling request took 290.637231ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:29:59.562728       1 request.go:591] Throttling request took 338.986248ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:30:09.012570       1 request.go:591] Throttling request took 419.676173ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:30:19.270585       1 request.go:591] Throttling request took 355.943286ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:30:40.369073       1 request.go:591] Throttling request took 251.448724ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:30:51.019605       1 request.go:591] Throttling request took 329.512125ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:00.169268       1 request.go:591] Throttling request took 596.340432ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:05.519530       1 request.go:591] Throttling request took 181.186876ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:14.868701       1 request.go:591] Throttling request took 545.271603ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:23.119681       1 request.go:591] Throttling request took 388.854376ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:31.669300       1 request.go:591] Throttling request took 246.905561ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:40.369208       1 request.go:591] Throttling request took 374.552037ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:44.791522       1 request.go:591] Throttling request took 93.770177ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
I0412 15:31:59.091661       1 request.go:591] Throttling request took 495.377239ms, request: POST:https://kube-apiserver/api/v1/namespaces/ws-xxxxx/pods/xxxx-deployment-78864894dd-2xdfd/eviction
```

The eviction request is repeated every 5 to 10 seconds.

**What you expected to happen**:

The machine controller manager should reduce the frequency of pod eviction calls if the termination of a machine takes a long time.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Internal reference:  see live issue #1570

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

/cc @kon-angelo

### PR DESCRIPTION
**Pull request by thiyyakat**
**What this PR does / why we need it**:

The PR changes the way pods are listed before eviction, by using a `PodInformer` which uses a local cache rather than directly querying the kube-apiserver/etcd. The pods are listed only after the cache has synced. 

**Which issue(s) this PR fixes**:
Fixes #703 

**Special notes for your reviewer**:

Impact of changes tested by running pods  configuring a PDB with `maxUnavailable` set to 0, on a cluster with 20 machines, and deleting all the machines, thereby initiating drain. Without change, peak traffic recorded was 8.51 MB/s. With change, peak traffic recorded was 1.48 MB/s. 

Screenshot 2024-10-21 at 1 10 05 PM

Integration tests run for providers AWS and Azure completed successfully.

Additionally, to manually check if cache for `podInformer` syncs successfully before the `podLister.List()` call,`time.Sleep( 30 * time.Second)` was introduced before calling `RunCordonOrUncordon()`, and a new pod (default/nginx-pod2 ) was deployed during the sleep period. Logs were added to print the names of all pods on the node returned by the podLister.  After triggering the deletion of the machine, the machine entered the drain flow, and after the sleep the new pod's name was logged.

```
I1023 16:13:08.044770   91923 machine_util.go:1182] (drainNode) Invoking RunDrain, forceDeleteMachine: false, forceDeletePods: false, timeOutDuration: 5m0s
I1023 16:13:08.044894   91923 drain.go:238] ABOUT TO SLEEP for 30s
I1023 16:13:43.861554   91923 drain.go:369] Found pod default/nginx-pod2 
```

**Release note**:

```other operator
MCM will use an `informer` instead of the`clientset` to list pods in the drain logic. This will reduce the load on etcd/kube-apiserver.
```

### CODE REVIEW

File: pkg/util/provider/drain/drain.go [hunk 1]
```diff
@@ -232,20 +239,26 @@ func (o *Options) RunDrain(ctx context.Context) error {
 		klog.Errorf("Drain Error: Cordoning of node failed with error: %v", err)
 		return err
 	}
+	stopCh := make(chan struct{})
```
Comment (elankath) [inline pkg/util/provider/drain/drain.go:242]: We should not construct an empty `stopCh` here as it becomes useless for signalling. We should use a channel obtained from `context.WithTimeout` using the drain timeout passed to `NewDrainOptions`. And then use the `Done()` method on the returned context to get the `stopCh`.

File: pkg/util/provider/drain/drain.go [hunk 2]
```diff
@@ -232,20 +239,26 @@ func (o *Options) RunDrain(ctx context.Context) error {
...
+		return err
+	}
 
 	err := o.deleteOrEvictPodsSimple(drainContext)
 	return err
 }
 
 func (o *Options) deleteOrEvictPodsSimple(ctx context.Context) error {
-	pods, err := o.getPodsForDeletion(ctx)
+	pods, err := o.getPodsForDeletion()
```
Comment (elankath) [inline pkg/util/provider/drain/drain.go:254]: we should use the ctx created from the approach mentioned in last comment.

File: pkg/util/provider/drain/drain.go (hunk 1 above)
Comment (elankath) [reply pkg/util/provider/drain/drain.go:242]: PS: There is already a context created for this a little later in `RunDrain`. `	drainContext, cancelFn := context.WithDeadline(ctx, o.drainStartedOn.Add(o.Timeout))
`

We should use the `Done()` channel from this.

File: pkg/util/provider/drain/drain.go [hunk 3]
```diff
@@ -337,32 +350,35 @@ func (ps podStatuses) Message() string {
...
-	for _, pod := range podList.Items {
-		podOk := true
-		for _, filt := range []podFilter{mirrorPodFilter, o.localStorageFilter, o.unreplicatedFilter, o.daemonsetFilter} {
-			filterOk, w, f := filt(pod)
-
-			podOk = podOk && filterOk
-			if w != nil {
-				ws[w.string] = append(ws[w.string], pod.Name)
+	for _, pod := range podList {
+		if pod.Spec.NodeName == o.nodeName {
```
Comment (elankath) [inline pkg/util/provider/drain/drain.go:366]: Just use a not-nil check where and continue isntead of nesting.

**Review by elankath — CHANGES_REQUESTED** [review]
looks good. small changes requested.

File: pkg/util/provider/app/app.go [hunk 4]
```diff
@@ -279,6 +279,7 @@ func StartControllers(s *options.MCServer,
 		targetCoreInformerFactory.Storage().V1().VolumeAttachments(),
 		machineSharedInformers.MachineClasses(),
 		machineSharedInformers.Machines(),
+		targetCoreInformerFactory.Core().V1().Pods(),
```
Comment (aaronfern) [inline pkg/util/provider/app/app.go:282]: Nit: Can you move this a few lines up so that all `InformerFactory`s are together?

File: pkg/util/provider/drain/drain.go [hunk 5]
```diff
@@ -337,21 +348,25 @@ func (ps podStatuses) Message() string {
...
 // getPodsForDeletion returns all the pods we're going to delete.  If there are
 // any pods preventing us from deleting, we return that list in an error.
-func (o *Options) getPodsForDeletion(ctx context.Context) (pods []corev1.Pod, err error) {
-	podList, err := o.client.CoreV1().Pods(metav1.NamespaceAll).List(ctx, metav1.ListOptions{
-		FieldSelector: fields.SelectorFromSet(fields.Set{"spec.nodeName": o.nodeName}).String()})
+func (o *Options) getPodsForDeletion() (pods []corev1.Pod, err error) {
+	podList, err := o.podLister.List(labels.Everything())
 	if err != nil {
-		return pods, err
+		return nil, err
```
Comment (elankath) [inline pkg/util/provider/drain/drain.go:354]: minor nit: with named return params, you don't need explicit valued return. Just a bare `return` is sufficient.

**Review by elankath — APPROVED** [review]
/lgtm . Please run IT.

**Review by rishabh-11 — APPROVED** [review]
/lgtm
