### PR TITLE
Trigger removal of CA tainted machine without waiting for replica change

### LINKED ISSUE #971: kube-proxy pod not healthy - scale down CA tainted node ASAP
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority 2

**What happened**:
kube-proxy reports Node as not healthy when CA taints a Node for deletion. MCM does not remove this node if replica count of MachineDeployment is unchanged.

k8s gardener live issue 6101            

**What you expected to happen**:
The machine set controller should mark this node as a stale node and scale it down and scale-up a fresh machine and node to match the replica count.

**How to reproduce it (as minimally and precisely as possible)**:

Taint a k8s node with the CA deletion taint and add the machine name to the triggered for deletion annotation on the machine deployment.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by elankath**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #971

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
CA tainted node is removed as soon as possible by MachineSet controller 
```

### CODE REVIEW

**Comment by elankath** [comment]
# Test Log

## Situation Before Fix

### Initial Cluster State

#### List MCD and MC
```
machine-controller-manager ➤ k get mcd; k get mc #list                                        git:master
NAME                                READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-one-zone-z1                                                 3m32s
shoot--i034796--aw-sys-comp-z1      2       2         2            2           3m32s
shoot--i034796--aw-three-zones-z1   1       1         1            1           3m32s
shoot--i034796--aw-three-zones-z2                                              3m32s
shoot--i034796--aw-three-zones-z3                                              3m32s
NAME                                            STATUS    AGE     NODE
shoot--i034796--aw-sys-comp-z1-6c5b8-g6phv      Running   3m28s   shoot--i034796--aw-sys-comp-z1-6c5b8-g6phv
shoot--i034796--aw-sys-comp-z1-6c5b8-p5sdh      Running   3m27s   shoot--i034796--aw-sys-comp-z1-6c5b8-p5sdh
shoot--i034796--aw-three-zones-z1-6547d-wt5qw   Running   3m28s   shoot--i034796--aw-three-zones-z1-6547d-wt5qw
```

### Annotate Machine Like CA Does but don't change replicas

```
k annotate mcd shoot--i034796--aw-three-zones-z1 "node.machine.sapcloud.io/trigger-deletion-by-mcm=shoot--i034796--aw-three-zones-z1-6547d-wt5qw"
machinedeployment.machine.sapcloud.io/shoot--i034796--aw-three-zones-z1 annotated
```

### Log acknowledges this but MachineSet controller doesn't react

```
I0310 07:51:39.098225  141546 deployment.go:435] Processing the machinedeployment "shoot--i034796--aw-three-zones-z1" (with replicas 1)
I0310 07:51:39.098305  141546 deployment.go:621] MachineDeployment "shoot--i034796--aw-three-zones-z1" has #1 machine(s) marked for deletion, triggerForDeletionMachineNames=[shoot--i034796--aw-three-zones-z1-6547d-wt5qw]
```

### Explicitly Reduce MCD replicas by 1

```
k scale mcd shoot--i034796--aw-three-zones-z1 --replicas=0       git:master
machinedeployment.machine.sapcloud.io/shoot--i034796--aw-three-zones-z1 scaled
```

### MachineSet controller now acts as expected and removes MC

#### Log
```
I0310 07:53:37.850483  141546 machineset.go:500] Processing the machineset "shoot--i034796--aw-three-zones-z1-6547d" with replicas 0 associated with machine class: ""
I0310 07:53:37.850644  141546 machineset.go:427] Too many replicas for  shoot--i034796--aw/shoot--i034796--aw-three-zones-z1-6547d, need 0, deleting 1
I0310 07:53:37.850675  141546 machineset_util.go:210] Machine "shoot--i034796--aw-three-zones-z1-6547d-wt5qw" has machinepriority.machine.sapcloud.io annotation set to 1
I0310 07:53:37.850683  141546 machineset_util.go:217] Machine "shoot--i034796--aw-three-zones-z1-6547d-wt5qw" needs to be deleted
```
#### Status
```
k get mcd; k get mc #list                                        git:master
NAME                                READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-one-zone-z1                                                 7m44s
shoot--i034796--aw-sys-comp-z1      2       2         2            2           7m44s
shoot--i034796--aw-three-zones-z1                                              7m44s
shoot--i034796--aw-three-zones-z2                                              7m44s
shoot--i034796--aw-three-zones-z3                                              7m44s
NAME                                         STATUS    AGE     NODE
shoot--i034796--aw-sys-comp-z1-6c5b8-g6phv   Running   7m40s   shoot--i034796--aw-sys-comp-z1-6c5b8-g6phv
shoot--i034796--aw-sys-comp-z1-6c5b8-p5sdh   Running   7m39s   shoot--i034796--aw-sys-comp-z1-6c5b8-p5sdh
```

## Situation After Fix

Initially we had a really complicated fix that adjusted both CA and MCM to take into account the situation where CA "changes its mind" about deleting the machine. But this was too complicated and ran into several issues and so we took brain-dead, simple fix in MCM where a machine tainted by the CA is marked as stale by the machine set controller. This solves the problem as machine is now deleted ASAP and kube-proxy will not get the chance to report it as unhealthy.

### Initial Cluster State

```
machine-controller-manager ➤ k get mcd; k get mc #list                                       git:kp-fix*
NAME                                READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-one-zone-z1                                                 57m
shoot--i034796--aw-sys-comp-z1      2       2         2            2           57m
shoot--i034796--aw-three-zones-z1   1       1         1            1           57m
shoot--i034796--aw-three-zones-z2                                              57m
shoot--i034796--aw-three-zones-z3                                              57m
NAME                                            STATUS    AGE     NODE
shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g      Running   3m47s   shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g
shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr      Running   3m48s   shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr
shoot--i034796--aw-three-zones-z1-6547d-lbc5c   Running   2m18s   shoot--i034796--aw-three-zones-z1-6547d-lbc5c
```

### Simulate CA tainting

```
k annotate mcd shoot--i034796--aw-three-zones-z1 "node.machine.sapcloud.io/trigger-deletion-by-mcm=shoot--i034796--aw-three-zones-z1-6547d-lbc5c"
```

### Machine is moved immediately to Terminating without waiting for replica change


```
k get mcd; k get mc #list                                       git:kp-fix*
NAME                                READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
shoot--i034796--aw-one-zone-z1                                                 59m
shoot--i034796--aw-sys-comp-z1      2       2         2            2           59m
shoot--i034796--aw-three-zones-z1           1         2                        59m
shoot--i034796--aw-three-zones-z2                                              59m
shoot--i034796--aw-three-zones-z3                                              59m
NAME                                            STATUS        AGE     NODE
shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g      Running       5m      shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g
shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr      Running       5m1s    shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr
shoot--i034796--aw-three-zones-z1-6547d-lbc5c   Terminating   3m31s   shoot--i034796--aw-three-zones-z1-6547d-lbc5c
shoot--i034796--aw-three-zones-z1-6547d-sfj9g                 2s
```

### Final Cluster State

```
k get mc                                                        git:kp-fix*
NAME                                            STATUS    AGE     NODE
shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g      Running   5m30s   shoot--i034796--aw-sys-comp-z1-6c5b8-jq79g
shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr      Running   5m31s   shoot--i034796--aw-sys-comp-z1-6c5b8-sqzzr
shoot--i034796--aw-three-zones-z1-6547d-sfj9g   Running   32s     shoot--i034796--aw-three-zones-z1-6547d-sfj9g
```

### Relevant MCM Log


```
```
I0310 07:32:34.427722  139138 deployment.go:621] MachineDeployment "shoot--i034796--aw-three-zones-z1" has #1 machine(s) marked for deletion, triggerForDeletionMachineNames=[shoot--i034796--aw-three-zones-z1-6547d-lbc5c]
I0310 07:32:34.435595  139138 machineset.go:350] Deleting stale machines [shoot--i034796--aw-three-zones-z1-6547d-lbc5c]   

I0310 07:32:34.440094  139138 event.go:377] Event(v1.ObjectReference{Kind:"MachineSet", Namespace:"shoot--i034796--aw", Name:"shoot--i034796--aw-three-zones-z1-6547d", UID:"eea0b137-645e-4bd8-88a3-f7cafd54fc52", APIVersion:"machine.sapcloud.io/v1alpha1", ResourceVersion:"986", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted machine: shoot--i034796--aw-three-zones-z1-6547d-lbc5c

I0310 07:32:34.456524  139138 deployment.go:669] Updated MachineDeployment "shoot--i034796--aw-three-zones-z1" with #0 machine names still pending deletion, triggerDeletionAnnotValue=""

I0310 07:32:34.460161  139138 machineset.go:710] Delete machine from machineset "shoot--i034796--aw-three-zones-z1-6547d-lbc5c"
I0310 07:32:34.460240  139138 machineset.go:380] Too few replicas for MachineSet shoot--i034796--aw-three-zones-z1-6547d, need 1, creating 1
I0310 07:32:34.462233  139138 deployment.go:435] Processing the machinedeployment "shoot--i034796--aw-three-zones-z1" (with replicas 1)
I0310 07:32:34.466029  139138 controller_utils.go:595] Controller shoot--i034796--aw-three-zones-z1-6547d created machine shoot--i034796--aw-three-zones-z1-6547d-sfj9g

I0310 07:32:34.466261  139138 event.go:377] Event(v1.ObjectReference{Kind:"MachineSet", Namespace:"shoot--i034796--aw", Name:"shoot--i034796--aw-three-zones-z1-6547d", UID:"eea0b137-645e-4bd8-88a3-f7cafd54fc52", APIVersion:"machine.sapcloud.io/v1alpha1", ResourceVersion:"986", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created Machine: shoot--i034796--aw-three-zones-z1-6547d-sfj9g

I0310 07:32:34.470251  139138 machineset.go:350] Deleting stale machines [shoot--i034796--aw-three-zones-z1-6547d-lbc5c] 

```

File: pkg/util/provider/machineutils/utils.go [hunk 1]
```diff
@@ -101,3 +101,23 @@ func IsMachineFailedOrTerminating(machine *v1alpha1.Machine) bool {
...
+}
+
+// IsMachineFailed checks if machine has failed
+func IsMachineFailed(p *v1alpha1.Machine) bool {
+	return p.Status.CurrentStatus.Phase == v1alpha1.MachineFailed
+}
+
+// IsMachineTriggeredForDeletion checks if machine was triggered for deletion
+func IsMachineTriggeredForDeletion(m *v1alpha1.Machine) bool {
+	return m.Annotations[MachinePriority] == "1" || m.Annotations[TriggerDeletionByMCM] == "true"
```
Comment (aaronfern) [inline pkg/util/provider/machineutils/utils.go:122]: I wondered why do we need to check for `m.Annotations[TriggerDeletionByMCM] == "true"`?
This annotation is either added to the `mcd` (by CA) or to a node (by user)
I don't see any code that adds this annotation to the machine unless I missed something

**Review by aaronfern — COMMENTED** [review]
Thanks for the PR!
I just have one question to clarify

File: pkg/util/provider/machineutils/utils.go (hunk 1 above)
Comment (elankath) [reply pkg/util/provider/machineutils/utils.go:122]: This annotation was added to the `Node` object to trigger for deletion. So I thought for symmetry it should also be added to `Machine` object.

**Review by takoverflow — APPROVED** [review]

File: pkg/util/provider/machineutils/utils.go [hunk 2]
```diff
@@ -101,3 +101,23 @@ func IsMachineFailedOrTerminating(machine *v1alpha1.Machine) bool {
 	}
 	return false
 }
+
+// IsMachineActive checks if machine was active
+func IsMachineActive(p *v1alpha1.Machine) bool {
```
Comment (unmarshall) [inline pkg/util/provider/machineutils/utils.go:106]: you can simplify it:
```go
return ! (p.Status.CurrentPhase.Phase == v1alpha1.MachineFailed || p.Status.CurrentStatus.Phase == v1alpha1.MachineTerminating)

```

File: pkg/util/provider/machineutils/utils.go (hunk 1 above)
Comment (unmarshall) [reply pkg/util/provider/machineutils/utils.go:122]: Current doc string:
```go
// TriggerDeletionByMCM annotation on the node would trigger the deletion of the corresponding machine object in the control cluster
// This annotation can also be set on the MachineDeployment and contains the machine names for which deletion should be triggered.
// This feature is leveraged by the CA-MCM cloud provider.
TriggerDeletionByMCM = "node.machine.sapcloud.io/trigger-deletion-by-mcm"
```
As per the doc string the annotation can be placed on MCD or on the Node. Apart from symmetry is there any reason to place this label on the `Machine`?

File: pkg/controller/machineset_test.go [hunk 3]
```diff
@@ -879,6 +841,40 @@ var _ = Describe("machineset", func() {
...
+			Expect(len(machines.Items)).To(Equal(int(testMachineSet.Spec.Replicas)))
+
+			beforeMachines := []*machinev1.Machine{staleMachine, testActiveMachine2, testActiveMachine3}
+			err := c.manageReplicas(context.TODO(), beforeMachines, testMachineSet)
+			Expect(err).Should(BeNil())
+			waitForCacheSync(stop, c)
+
+			_, err = c.controlMachineClient.Machines(testNamespace).Get(context.Background(), staleMachine.Name, metav1.GetOptions{})
+			// MachinePriority=1 staleMachine is no longer found
+			//Expect(staleMachine).Should(BeNil())
```
Comment (unmarshall) [inline pkg/controller/machineset_test.go:867]: can you remove this commented code line?

**Review by unmarshall — COMMENTED** [review]
Minor comments.

File: pkg/controller/machineset_test.go (hunk 3 above)
Comment (elankath) [reply pkg/controller/machineset_test.go:867]: Some times `Node` may not be registered but operator wants MCM to trigger deletion before the machine timeout. This will assist in that case.

**Review by aaronfern — APPROVED** [review]
