### PR TITLE
Fixing the issue where a rapid scale up and scale down can result in a cordoned machine in the cluster.

### LINKED ISSUE #1085: Rapid scale up and scale down of a MCD result in a cordoned machine
**How to categorize this issue?**

/area auto-scaling
/kind bug
/priority 3

**What happened**:
We found a bug recently where a rapid scale up and scale down can result in a cordoned machine in the cluster.
This is due to the scale down logic we have with CA, and the recent changes to `manageReplicas()` in the machineSet controller

The case happens when CA scales down a MCD followed quickly with scaling up the same MCD before the MCD controller notices the replica change and start reconciliation. The result is the MCD ending up with the same number of replicas that it started off with, causing the MCD controller not to have any work to do since from it's point of view, the MCD replicas have not changed.
As part of the scale down operation, CA will cordon an underutilised node. This node just remains part of the cluster as MCM makes no further attempt to remove it

Problem example
```
T0:
	We have a mcd with 6 replicas and machines M1…M6
	MCD rep=6

T1:
	CA finds M1 unneeded. Reduces mcd replicas to 5, adds a mc (MC1) to trigger-for-deletion annotation on MCD, and cordons this machine
	MCD rep=5; trigger-for-deletion-annotation=M1
	M1 cordoned by CA
	(MCD controller does not run - for whatever reason)

T2: 
	CA increasesMCD rep=6 
	(MCD controller still does not run - for whatever reason)

T3:
	MCD controller start here
	sees that rep=6 (no change). No work done
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by r4mek**
**What this PR does / why we need it**:
This PR contains a fix for the issue where a rapid scale up and scale down can result in a cordoned machine in the cluster.

The case happens when CA scales down a MCD followed quickly with scaling up the same MCD before the MCD controller notices the replica change and start reconciliation. The result is the MCD ending up with the same number of replicas that it started off with, causing the MCD controller not to have any work to do since from it's point of view, the MCD replicas have not changed.
As part of the scale down operation, CA will cordon an underutilised node. This node just remains part of the cluster as MCM makes no further attempt to remove it

**Which issue(s) this PR fixes**:
Fixes #1085, #1084

**Special notes for your reviewer**:
There is also a PR raised on `gardener/autoscaler` which has the changes from the autoscaler and is also required to fix the issue. PR(https://github.com/gardener/autoscaler/pull/401)

**Release note**:

```other operator
Fixing an issue where a rapid scale up and scale down can result in a cordoned machine in the cluster.
```

### CODE REVIEW

File: pkg/util/provider/machineutils/utils.go [hunk 1]
```diff
@@ -63,6 +63,10 @@ const (
 	// This feature is leveraged by the CA-MCM cloud provider.
 	TriggerDeletionByMCM = "node.machine.sapcloud.io/trigger-deletion-by-mcm"
 
+	// LastReplicaChangeAnnotation contains the timestamp of last replica change in the machine deployment.
+	// This annotation is used so that MCS only deletes the machines for which it has observed change in replicas.:w
```
Comment (thiyyakat) [inline pkg/util/provider/machineutils/utils.go]:
```suggestion
	// This annotation is used so that MCS only deletes the machines for which it has observed change in replicas.
```

File: pkg/controller/machineset_test.go [hunk 2]
```diff
@@ -1813,4 +1812,133 @@ var _ = Describe("machineset", func() {
...
+				},
+				Status: machinev1.MachineStatus{
+					CurrentStatus: machinev1.CurrentStatus{
+						Phase: MachineRunning,
+					},
+				},
+			}
+		})
+
+		It("It should delete the marked machines with no change in machineSet replicas", func() {
```
Comment (thiyyakat) [inline pkg/controller/machineset_test.go]: You don't need to use "It" in the description.
```suggestion
		It("should delete the marked machines with no change in machineSet replicas", func() {
```

File: pkg/controller/machineset_test.go [hunk 3]
```diff
@@ -1813,4 +1812,133 @@ var _ = Describe("machineset", func() {
...
+			_, Err1 := c.controlMachineClient.Machines(testNamespace).Get(context.TODO(), testRunningMachine1.Name, metav1.GetOptions{})
+			_, Err2 := c.controlMachineClient.Machines(testNamespace).Get(context.TODO(), testRunningMachine2.Name, metav1.GetOptions{})
+
+			Expect(Err1).Should(Not(BeNil()))
+			Expect(k8sError.IsNotFound(Err1)).Should(BeTrue())
+			Expect(Err2).Should(Not(BeNil()))
+			Expect(k8sError.IsNotFound(Err2)).Should(BeTrue())
+		})
+
+		It("It should delete the marked machines after reducing change in machineSet replicas", func() {
```
Comment (thiyyakat) [inline pkg/controller/machineset_test.go]: Same here. No need to say "It".

File: pkg/controller/deployment_test.go [hunk 4]
```diff
@@ -2171,4 +2171,194 @@ var _ = Describe("machineDeployment", func() {
...
+
+				waitForCacheSync(stop, c)
+				machine1, _ := c.controlMachineClient.Machines(testNamespace).Get(context.Background(), testMachine1.Name, metav1.GetOptions{})
+				machine2, _ := c.controlMachineClient.Machines(testNamespace).Get(context.Background(), testMachine2.Name, metav1.GetOptions{})
+				Expect(machine1.Annotations[machineutils.MachinePriority]).To(Equal("1"))
+				Expect(machine1.Annotations[machineutils.LastReplicaChangeAnnotation]).To(Equal(ts))
+				Expect(machine2.Annotations[machineutils.MachinePriority]).To(Equal("1"))
+				Expect(machine2.Annotations[machineutils.LastReplicaChangeAnnotation]).To(Equal(ts))
+			},
+			Entry("mark the machines named in TriggerDeletionByMCM annotation for deletion by setting their MachinePriority annotation to 1 and also set the LastReplicaChangeAnnotation on them same as that is passed with the annotation",
```
Comment (thiyyakat) [inline pkg/controller/deployment_test.go]:
```suggestion
			Entry("mark the machines named in TriggerDeletionByMCM annotation for deletion by setting their MachinePriority annotation to 1 and also set their LastReplicaChangeAnnotation to the same value passed with the annotation",
```

File: pkg/controller/deployment.go [hunk 5]
```diff
@@ -693,9 +697,9 @@ func (dc *controller) setMachinePriorityAnnotationAndUpdateTriggeredForDeletion(
 	}
 	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdAdjust, metav1.UpdateOptions{})
 	if err != nil {
-		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
+		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNamesWithTS), triggerDeletionAnnotValue)
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]:
```suggestion
		klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNamesWithTS), triggerDeletionAnnotValue)
```

File: pkg/controller/machineset.go [hunk 6]
```diff
@@ -335,6 +335,31 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
+					continue
+				}
+				machineLRCA, err := time.Parse(time.RFC3339, machine.Annotations[machineutils.LastReplicaChangeAnnotation])
+				if err != nil {
+					continue
+				}
+				if machineLRCA.Before(machineSetLRCA) || machineLRCA.Equal(machineSetLRCA) {
+					scaleDownMachines = append(scaleDownMachines, machine)
+				}
+			}
```
Comment (thiyyakat) [inline pkg/controller/machineset.go]: Could you please add a comment here explaining the change?

File: pkg/controller/machineset.go [hunk 7]
```diff
@@ -335,6 +335,31 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
 		return nil
 	}
 
+	scaleDownMachines := []*v1alpha1.Machine{}
+	if machineSet.Annotations[machineutils.LastReplicaChangeAnnotation] != "" {
+		machineSetLRCA, err := time.Parse(time.RFC3339, machineSet.Annotations[machineutils.LastReplicaChangeAnnotation])
```
Comment (thiyyakat) [inline pkg/controller/machineset.go]: The `err` is not handled. Maybe log the err as a warning here?

File: pkg/controller/machineset.go [hunk 8]
```diff
@@ -335,6 +335,31 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
+				machineLRCA, err := time.Parse(time.RFC3339, machine.Annotations[machineutils.LastReplicaChangeAnnotation])
+				if err != nil {
+					continue
+				}
+				if machineLRCA.Before(machineSetLRCA) || machineLRCA.Equal(machineSetLRCA) {
+					scaleDownMachines = append(scaleDownMachines, machine)
+				}
+			}
+			if len(scaleDownMachines) >= 1 {
+				klog.V(3).Infof("Deleting stale machines %s", getMachineKeys(scaleDownMachines))
```
Comment (takoverflow) [inline pkg/controller/machineset.go]: Please change these logs to not call them stale machines.
Similarly for the below error for the terminate call as well.

File: pkg/controller/deployment.go [hunk 9]
```diff
@@ -643,22 +644,24 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+	var triggerForDeletionMachineNamesWithTS, skipTriggerForDeletionMachineNames []string
+	triggerForDeletionMachineNamesWithTS = annotations.GetMachineNamesTriggeredForDeletion(mcd)
+	if len(triggerForDeletionMachineNamesWithTS) == 0 {
 		return nil
 	}
-	klog.V(3).Infof("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(triggerForDeletionMachineNames), triggerForDeletionMachineNames)
-	for _, machineName := range triggerForDeletionMachineNames {
+	klog.V(3).Infof("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(triggerForDeletionMachineNamesWithTS), triggerForDeletionMachineNamesWithTS)
+	for _, machineNameWithTS := range triggerForDeletionMachineNamesWithTS {
+		parts := strings.Split(machineNameWithTS, "~")
```
Comment (aaronfern) [inline pkg/controller/deployment.go]: Add a warning is len(parts) != 2 and continue to the next if this is the case

File: pkg/controller/deployment.go [hunk 10]
```diff
@@ -643,22 +644,24 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		machineName, machineDeletionTS := parts[0], parts[1]
```
Comment (aaronfern) [inline pkg/controller/deployment.go]: Please parse machineDeletionTS to ensure it is a valid timestamp. if it is not, log it and continue to the next

Also, if annotation is invalid, please add machine to `skipTriggerForDeletionMachineNames`

File: pkg/controller/deployment.go [hunk 11]
```diff
@@ -670,6 +673,7 @@ func (dc *controller) setMachinePriorityAnnotationAndUpdateTriggeredForDeletion(
 			mcAdjust.Annotations = make(map[string]string)
 		}
 		mcAdjust.Annotations[machineutils.MachinePriority] = "1"
+		mcAdjust.Annotations[machineutils.LastReplicaChangeAnnotation] = machineDeletionTS
```
Comment (aaronfern) [inline pkg/controller/deployment.go]: Add a check to not update LastReplicaChangeAnnotation if already set
Also add a log line is TS is already set and continue

File: pkg/controller/deployment.go [hunk 12]
```diff
@@ -643,22 +644,24 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
 }
 
 func (dc *controller) setMachinePriorityAnnotationAndUpdateTriggeredForDeletion(ctx context.Context, mcd *v1alpha1.MachineDeployment) error {
```
Comment (aaronfern) [inline pkg/controller/deployment.go]: Add another function that is called by this one `func ComputeMachineTriggerDeletionData(mcd) triggerDeletionData` that takes care of computing the machineNames/timestamps and other data necessary for application from the trigger deletionAnnotation.

The struct can be as follows
```
type triggerDeletionData struct{
	machineNamesWithTS []string
	skipMachineNamesWithTS []string
	machineMarkedDeletionTimes map[string]time.Time (consider map[string]string based on implementation)
}
```

Also, add another method on this structure to give you annotations that you should add to the machineDeployment. This method can be called `latestTriggerDeletionAnnotationValue()`

Comment (aaronfern) [inline pkg/controller/deployment.go]: Please rename this function to be more accurate to what it is doing
```suggestion
func (dc *controller) updateMachineAndMachineDeploymentDeletionAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) error {
```

File: pkg/controller/deployment_sync.go [hunk 13]
```diff
@@ -552,6 +553,7 @@ func (dc *controller) scaleMachineSet(ctx context.Context, is *v1alpha1.MachineS
 	var err error
 	if sizeNeedsUpdate || annotationsNeedUpdate {
 		isCopy.Spec.Replicas = newScale
+		isCopy.Annotations[machineutils.LastReplicaChangeAnnotation] = deployment.Annotations[machineutils.LastReplicaChangeAnnotation]
```
Comment (aaronfern) [inline pkg/controller/deployment_sync.go]: Please change the annotation name to `machine.sapcloud.io/last-deployment-replica-change-time-by-scaler`
This is to be used on machineDeployments and machineSets only

File: pkg/controller/deployment.go (hunk 11 above)
Comment (aaronfern) [inline pkg/controller/deployment.go]: Please add a new annotation to be used on machines. It can be called `machine.sapcloud.io/mark-deletion-time`

File: pkg/controller/machineset.go [hunk 14]
```diff
@@ -335,6 +335,31 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
+				if err := c.terminateMachines(ctx, scaleDownMachines, machineSet); err != nil {
+					klog.Errorf("failed to terminate stale machines for machineset %s: %v", machineSet.Name, err)
+				}
+			}
+		}
+	}
+
```
Comment (aaronfern) [inline pkg/controller/machineset.go]: Move this to a function. Accept `allMachines` and `machineSet.Annotations[machineutils.LastReplicaChangeAnnotation]`, and it should return a list of machineNames to delete

File: pkg/controller/machineset.go
Comment (aaronfern) [inline pkg/controller/machineset.go:331]: As part of manageReplicas, please make the following 2 changes
1. Update the sorting function in `getMachinesToDelete()` to now consider the timestamp set on the `mark-for-deletion` annotation
2. Do not delete machines inside the `machinesWithoutUpdateSuccessfulLabelDiff > 0` block, but rather store all the machined intended to be deleted in a list and delete them later in at the end of the method after also computing stale machines

File: pkg/controller/deployment.go (hunk 10 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: If I add machine to `skipTriggerForDeletionMachineNames`, then we won't mark the machine but since the replica is already reduced, we might delete a different machine. This would be a side effect observed.

File: pkg/controller/controller_utils.go [hunk 15]
```diff
@@ -767,13 +767,22 @@ func (s ActiveMachines) Less(i, j int) bool {
 		v1alpha1.MachineRunning:          6,
 	}
 
-	// Case-1: Initially we try to prioritize machine deletion based on
-	// machinePriority annotation.
-	// Case-2: If both priorities are equal, then we look at their machinePhase
+	// Case-1: Initially we try to prioritize machine deletion based on machinePriority annotation.
+	// Case-2: If both priorities are equal, then we at their MarkedForDeletionTime annotation
```
Comment (takoverflow) [inline pkg/controller/controller_utils.go]:
```suggestion
	// Case-2: If both priorities are equal, then we pick the one with older MarkedForDeletionTime annotation
```

File: pkg/controller/controller_utils.go [hunk 16]
```diff
@@ -767,13 +767,22 @@ func (s ActiveMachines) Less(i, j int) bool {
...
+	// Case-3: If both don't have the MarkedForDeletionTime annotation, then we look at their machinePhase
 	// and prioritize as mentioned in the above map
-	// Case-3: If both Case-1 & Case-2 is false, we prioritize based on creation time
+	// Case-3: If both Case-1, Case-2 & Case-3 is false, we prioritize based on creation time
```
Comment (takoverflow) [inline pkg/controller/controller_utils.go]:
```suggestion
	// Case-4: If all above cases are false, we prioritize based on creation time
```

File: pkg/controller/deployment.go [hunk 17]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
 	}
 }
 
-func (dc *controller) setMachinePriorityAnnotationAndUpdateTriggeredForDeletion(ctx context.Context, mcd *v1alpha1.MachineDeployment) error {
-	var triggerForDeletionMachineNames, skipTriggerForDeletionMachineNames []string
-	triggerForDeletionMachineNames = annotations.GetMachineNamesTriggeredForDeletion(mcd)
-	if len(triggerForDeletionMachineNames) == 0 {
+// Disclaimer: The logic in this function is based on the assumption that the scaler will put the correct time format in the annotation.
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: Isn't the invalid time format being parsed and checked by the scaler as well, in what scenario do you think the incorrect annotation would be applied?

Also this shouldn't be a docstring for this method, the docstring should rather explain what annotations are being added to what objects.

File: pkg/controller/deployment.go [hunk 18]
```diff
@@ -46,6 +47,12 @@ import (
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/machineutils"
 )
 
+type triggerDeletionData struct {
```
Comment (takoverflow) [inline pkg/controller/deployment.go:52]: Please add a docstring for the struct

File: pkg/controller/deployment.go [hunk 19]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+	machineMarkedDeletionTimes := make(map[*v1alpha1.Machine]string)
+
+	if len(oldTriggerDeletionAnnotationList) == 0 {
+		return nil
+	}
+	klog.V(3).Infof("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(oldTriggerDeletionAnnotationList), oldTriggerDeletionAnnotationList)
+
+	for _, machineNameWithTime := range oldTriggerDeletionAnnotationList {
+		parts := strings.Split(machineNameWithTime, "~")
+		// We add the machine name with time that has invalid format into skipMachineNamesWithTime to make sure that it is removed from the annotation
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: There is no `skipMachineNamesWithTime`, the comment needs to be corrected to state that this machine is not added to the new list.

File: pkg/controller/deployment.go [hunk 20]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if _, perr := time.Parse(time.RFC3339, machineDeletionTime); perr != nil {
+			klog.Infof("Invalid deletion time format %q for machine %q in MachineDeployment %q annotation", machineDeletionTime, machineName, mcd.Name)
+			continue
+		}
+		machine, gerr := dc.machineLister.Machines(dc.namespace).Get(machineName)
+		// The machine is deleted and hence we can remove it from the annotation.
+		if apierrors.IsNotFound(gerr) {
+			klog.V(4).Infof("Machine %q is not found in MachineDeployment %q - skip setting MachinePriority=1 annotation", machineName, mcd.Name)
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: This info string should be updated, since setting the p1 annotation doesn't happen here anymore
```suggestion
			klog.V(4).Infof("Machine %q is not found in MachineDeployment %q - skip adding to newTriggerDeletionAnnotationList", machineName, mcd.Name)
```

Similarly for the failed or terminating case as well.

File: pkg/controller/deployment.go [hunk 21]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+			machineDeepCopy.Annotations[machineutils.MarkedForDeletionTime] = machineDeletionTime
 		}
-		mcAdjust.Annotations[machineutils.MachinePriority] = "1"
-		_, err = dc.controlMachineClient.Machines(mcAdjust.Namespace).Update(ctx, mcAdjust, metav1.UpdateOptions{})
+		_, err = dc.controlMachineClient.Machines(machine.Namespace).Update(ctx, machineDeepCopy, metav1.UpdateOptions{})
 		if err != nil {
-			klog.Errorf("Failed to set MachinePriority=1 annotation on Machine %q of MachineDeployment %q: %v", machineName, mcd.Name, err)
-			return err
+			klog.Errorf("failed to set MachinePriority=1 annotation on Machine %q of MachineDeployment %q: %v", machine.Name, mcd.Name, err)
+			return
```
Comment (takoverflow) [inline pkg/controller/deployment.go:700]: Should we be returning here, in case updating one machine fails then the rest also don't get updated? WDYT

File: pkg/controller/deployment.go [hunk 22]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
 
-	triggerForDeletionMachineNames = sets.NewString(triggerForDeletionMachineNames...).Delete(skipTriggerForDeletionMachineNames...).List()
-	triggerDeletionAnnotValue := annotations.CreateMachinesTriggeredForDeletionAnnotValue(triggerForDeletionMachineNames)
-
-	mcdAdjust := mcd.DeepCopy()
-	if triggerDeletionAnnotValue != "" {
-		mcdAdjust.Annotations[machineutils.TriggerDeletionByMCM] = triggerDeletionAnnotValue
-	} else {
-		delete(mcdAdjust.Annotations, machineutils.TriggerDeletionByMCM)
+	mcdDeepCopy := mcd.DeepCopy()
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: IMO the deployment should be updated with the new annotation before the machines get marked. Consider the case where the machines have already been updated above but the deployment annotation update failed, now there's an inconsistency with respect to what CA sees and which machines are marked for removal already. WDYT?

File: pkg/controller/machineset.go [hunk 23]
```diff
@@ -418,44 +418,36 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
 		// but the ReplicaCount of newMachineSet has not increased yet.
 		// In such cases, we should not delete the machine immediately,
 		// otherwise it can cause unnecessary machine deletion and creation during in-place updates.
+	} else if machinesWithoutUpdateSuccessfulLabelDiff > 0 {
 		if machinesWithoutUpdateSuccessfulLabelDiff > BurstReplicas {
 			machinesWithoutUpdateSuccessfulLabelDiff = BurstReplicas
 		}
-		klog.V(2).Infof("Too many replicas for %v %s/%s, need %d, deleting %d", machineSet.Kind, machineSet.Namespace, machineSet.Name, (machineSet.Spec.Replicas), machinesWithoutUpdateSuccessfulLabelDiff)
-
 		logMachinesWithPriority1(machinesWithoutUpdateSuccessfulLabel)
```
Comment (takoverflow) [inline pkg/controller/machineset.go]: Can you update this function to print the machine's MarkDeletionTime as well when logging the p1 machine names.

File: pkg/controller/machineset.go [hunk 24]
```diff
@@ -889,3 +881,47 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
 
 	return machine, retryErr
 }
+
+// getMachinesMarkedForDeletion iterates through the machines and if a machine has MarkedForDeletionTime before LastDeploymentReplicaChangeByScalerTime of the machineSet,
```
Comment (takoverflow) [inline pkg/controller/machineset.go:891]: The docstring should also mention that failed machines are also added to the list of machines to be terminated.

File: pkg/controller/machineset.go [hunk 25]
```diff
@@ -889,3 +881,47 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+// that machine is added to the staleMachine list to be deleted.
+// This is done to have consistency between machineDeployment replica change and the machines marked for deletion.
+func getMachinesMarkedForDeletion(machineList []*v1alpha1.Machine, machineSet *v1alpha1.MachineSet) []*v1alpha1.Machine {
+	staleMachines := []*v1alpha1.Machine{}
+	machineSetLRCA, perr := time.Parse(time.RFC3339, machineSet.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime])
```
Comment (takoverflow) [inline pkg/controller/machineset.go:895]: Why check later if `perr` is nil. Why not return earlier if there's an error, if its to process machines that are already failed then that can be done outside the scope of this function. Combining them both with nested error handling isn't clean imo.

In case the concern is about the same machine being picked twice, anyways its being handled later by the `uniqueMachines()` call.

File: pkg/controller/machineset.go [hunk 26]
```diff
@@ -889,3 +881,47 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+			staleMachines = append(staleMachines, machine)
+			continue
+		}
+		if perr == nil {
+			if machine.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] == "" || machine.Annotations[machineutils.MachinePriority] != "1" {
+				continue
+			}
+			machineLRCA, err := time.Parse(time.RFC3339, machine.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime])
+			if err != nil {
+				klog.Infof("Error parsing time from %q with value %q of machine %q: %v", machineutils.MarkedForDeletionTime, machine.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime], machine.Name, err)
```
Comment (gagan16k) [inline pkg/controller/machineset.go]: Is this annotation, `machineutils.LastDeploymentReplicaChangeByScalerTime` ever set on a machine?
Shouldn't it be `machine.Annotations[machineutils.MarkedForDeletionTime]`

File: pkg/controller/machineset.go [hunk 27]
```diff
@@ -418,44 +418,36 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
+	// Snapshot the UIDs (ns/name) of the machines we're expecting to see
+	// deleted, so we know to record their expectations exactly once either
+	// when we see it as an update of the deletion timestamp, or as a delete.
+	// Note that if the labels on a machine/rs change in a way that the machine gets
+	// orphaned, the rs will only wake up after the expectations have
+	// expired even if other machines are deleted.
+	if err := c.expectations.ExpectDeletions(machineSetKey, getMachineKeys(staleMachines)); err != nil {
+		// TODO: proper error handling needs to happen here
+		klog.Errorf("failed expect deletions for machineset %s: %v", machineSet.Name, err)
 	}
```
Comment (gagan16k) [inline pkg/controller/machineset.go]: This should also be nested in the check `if len(staleMachines > 0` below this block

File: pkg/controller/machineset.go [hunk 28]
```diff
@@ -418,44 +418,36 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
 			}
 		}
 		return err
-	} else if machinesWithoutUpdateSuccessfulLabelDiff > 0 {
 		// During in-place updates, in the newMachineSet, it can happen that a machine has come from the oldMachineSet
 		// but the ReplicaCount of newMachineSet has not increased yet.
 		// In such cases, we should not delete the machine immediately,
 		// otherwise it can cause unnecessary machine deletion and creation during in-place updates.
```
Comment (gagan16k) [inline pkg/controller/machineset.go]: nit: could you move this comment to be in line with or into the  `} else if machinesWithoutUpdateSuccessfulLabelDiff > 0 {` block, for clarity

File: pkg/controller/deployment.go [hunk 29]
```diff
@@ -46,6 +47,12 @@ import (
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/machineutils"
 )
 
+type triggerDeletionData struct {
+	machineMarkedDeletionTimes            map[*v1alpha1.Machine]string
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: Consider  `map[string]string`, instead of relying on key `*v1alpha1.Machine`

File: pkg/controller/deployment_sync.go [hunk 30]
```diff
@@ -552,6 +553,7 @@ func (dc *controller) scaleMachineSet(ctx context.Context, is *v1alpha1.MachineS
 	var err error
 	if sizeNeedsUpdate || annotationsNeedUpdate {
 		isCopy.Spec.Replicas = newScale
+		isCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = deployment.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]
```
Comment (gagan16k) [inline pkg/controller/deployment_sync.go:558]: Would a check be necessary if the MCD has the annotation, as it might cause a `""` to be written on the machineset?  WDYT

File: pkg/controller/deployment.go (hunk 17 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: >Isn't the invalid time format being parsed and checked by the scaler as well, in what scenario do you think the incorrect annotation would be applied?

It is for cases where the annotation was applied manually or some other scaler using a different time format.

File: pkg/controller/deployment.go (hunk 21 above)
Comment (r4mek) [reply pkg/controller/deployment.go:700]: I think it should be fine as would most likely be a transient error or you see some other scenario?

File: pkg/controller/deployment.go (hunk 29 above)
Comment (takoverflow) [reply pkg/controller/deployment.go]: From what I could see, this is being done to avoid fetching the same machine object twice. But since its all fetched from the cache, I don't know how much the savings are.

Comment (r4mek) [reply pkg/controller/deployment.go]: This was done to avoid getting the object multiple times. Do you see any problems with the current approach?

File: pkg/controller/deployment.go (hunk 21 above)
Comment (takoverflow) [reply pkg/controller/deployment.go:700]: But what's the point in skipping adding the annotation for other machines if one fails.

Comment (r4mek) [reply pkg/controller/deployment.go:700]: If we don't return, we would go through with the machine deletion and end up deleting a machine which is not marked.

Comment (takoverflow) [reply pkg/controller/deployment.go:700]: Makes sense, thanks for clarifying!

File: pkg/controller/deployment.go (hunk 17 above)
Comment (takoverflow) [reply pkg/controller/deployment.go]: I'm talking with regards to the disclaimer, at any point the annotation can be modified to break the parsing, pointing it out doesn't really help.

This annotation is not meant for manual use, if someone ends up doing that its not MCM's responsibility.

As for the question of potentially other scalars reusing this annotation, they have to follow the specified format `{M1~T1,M2~T2}` otherwise they have no business using the annotation. So I don't see how this can be achieved

> // If that's not the case, we might run into issues where the machineDeployment replica was reduced but MCM rejects the deletion of the machine due to invalid time format in the annotation.
// TODO: We should think of a way to make this more robust in case of invalid time format in the annotation.

File: pkg/util/provider/machineutils/utils.go [hunk 31]
```diff
@@ -63,6 +63,13 @@ const (
 	// This feature is leveraged by the CA-MCM cloud provider.
 	TriggerDeletionByMCM = "node.machine.sapcloud.io/trigger-deletion-by-mcm"
```
Comment (takoverflow) [inline pkg/util/provider/machineutils/utils.go:65]: Maybe the docstring should specify the expected annotation value format as well
`[M1~T1,M2~T2...]`

File: pkg/controller/deployment.go (hunk 29 above)
Comment (gagan16k) [reply pkg/controller/deployment.go]: I see, but like @takoverflow mentioned, there might not be much savings as we would be fetching from the informer cache anyways. 
But I also do not see any issues with this, so will mark as resolved

File: pkg/controller/deployment.go [hunk 32]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+// computeMachineTriggerDeletionData computes the data related to machines that are triggered for deletion based on the annotation on the MachineDeployment.
+func (dc *controller) computeMachineTriggerDeletionData(mcd *v1alpha1.MachineDeployment) *triggerDeletionData {
+	oldTriggerDeletionAnnotationList := annotations.GetMachineNamesTriggeredForDeletion(mcd)
+	newTriggerDeletionAnnotationList := make([]string, 0)
+	machineMarkedDeletionTimes := make(map[*v1alpha1.Machine]string)
+
+	if len(oldTriggerDeletionAnnotationList) == 0 {
+		return nil
+	}
+	klog.V(3).Infof("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(oldTriggerDeletionAnnotationList), oldTriggerDeletionAnnotationList)
```
Comment (aaronfern) [inline pkg/controller/deployment.go]:
```suggestion
	klog.Warningf("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(oldTriggerDeletionAnnotationList), oldTriggerDeletionAnnotationList)
```

File: pkg/controller/controller_utils.go (hunk 15 above)
Comment (thiyyakat) [reply pkg/controller/controller_utils.go]: @r4mek , I see this comment is marked as resolved, but I don't see a change in the PR. Could you please check?

Comment (r4mek) [reply pkg/controller/controller_utils.go]: I haven't pushed the PR yet, was marking them as resolved to track the code changes

File: pkg/controller/deployment.go [hunk 33]
```diff
@@ -642,60 +649,102 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if len(parts) != 2 {
+			klog.Infof("Invalid machine name with time format %q in MachineDeployment %q annotation, expected format is <machineName1>~<deletionTime1>,<machineName2>~<deletionTime2>... skip setting MachinePriority=1 annotation", machineNameWithTime, mcd.Name)
+			continue
+		}
+		machineName, machineDeletionTime := parts[0], parts[1]
+		// We add the machine name with time that has invalid format into skipMachineNamesWithTime to make sure that it is removed from the annotation
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if _, perr := time.Parse(time.RFC3339, machineDeletionTime); perr != nil {
+			klog.Infof("Invalid deletion time format %q for machine %q in MachineDeployment %q annotation", machineDeletionTime, machineName, mcd.Name)
```
Comment (aaronfern) [inline pkg/controller/deployment.go]:
```suggestion
			klog.Warningf("Invalid deletion time format %q for machine %q in MachineDeployment %q annotation", machineDeletionTime, machineName, mcd.Name)
```

File: pkg/controller/deployment.go (hunk 22 above)
Comment (aaronfern) [reply pkg/controller/deployment.go]: An error with updating mcd would result in it being reconciled, so it should correct itself
Wrt the CA seeing an older value of the annotation, iiuc CA does not consider this annotation to determine if scale downs are needed or not, so it should not impact the whole system. Am I missing something?

Comment (takoverflow) [reply pkg/controller/deployment.go]:
```go
	mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = tgd.triggerDeletionAnnotationValue
	if mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] == "" {
		delete(mcdDeepCopy.Annotations, machineutils.TriggerDeletionByMCM)
	}
	_, err = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
```
This is updating the `TriggerDeletionByMCM` annotation which is checked by CA [here](https://github.com/gardener/autoscaler/blob/1a098032d9db4511ae8201cc26d9b4f668595062/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L1132) to compute `alreadyMarkedSet` of scale-down machines and subsequently the `RevisedScaledownAmount`.

Comment (r4mek) [reply pkg/controller/deployment.go]: >Consider the case where the machines have already been updated above but the deployment annotation update failed, now there's an inconsistency with respect to what CA sees and which machines are marked for removal already

It should be fixed in the next reconciliation. And what do you see happening if MCD is not updated/updated-later?

Comment (aaronfern) [reply pkg/controller/deployment.go]: As discussed on call, we can invert this order of mcd and mc updates, as this should functionally not change the logic, but the logical ordering of updates would be maintained

File: pkg/controller/machineset.go (hunk 25 above)
Comment (aaronfern) [reply pkg/controller/machineset.go:895]: As discussed on call, the `perr` check can be done early to have an early return
Additionally, the logic of adding failed machines to stale machines can be done in the caller and not part of this function.

File: pkg/controller/deployment.go [hunk 34]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+	for _, machineNameWithTime := range oldTriggerDeletionAnnotationList {
+		parts := strings.Split(machineNameWithTime, "~")
+		// We don't add the machine name with time that has invalid format into newTriggerDeletionAnnotationList to make sure that it is removed from the annotation
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if len(parts) != 2 {
+			klog.Infof("Invalid machine name with time format %q in MachineDeployment %q annotation, expected format is <machineName1>~<deletionTime1>,<machineName2>~<deletionTime2>... skip setting MachinePriority=1 annotation", machineNameWithTime, mcd.Name)
+			continue
+		}
+		machineName, machineDeletionTime := parts[0], parts[1]
+		// We don't add the machine name with time that has invalid format into newTriggerDeletionAnnotationList to make sure that it is removed from the annotation
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: What's the point in duplicating this comment when its already added at line 720

File: pkg/controller/machineset.go [hunk 35]
```diff
@@ -889,3 +890,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
 
 	return machine, retryErr
 }
+
+// getMachinesMarkedForDeletion iterates through the machines and if a machine is failed or has MarkedForDeletionTime before LastDeploymentReplicaChangeByScalerTime of the machineSet,
```
Comment (takoverflow) [inline pkg/controller/machineset.go]: Please update the doc-string to remove reference to failed machines for this function.

File: pkg/util/provider/machineutils/utils.go [hunk 36]
```diff
@@ -60,9 +60,16 @@ const (
 	NotManagedByMCM = "node.machine.sapcloud.io/not-managed-by-mcm"
 
 	// TriggerDeletionByMCM can be set on the MachineDeployment and contains the machine names for which deletion should be triggered.
```
Comment (takoverflow) [inline pkg/util/provider/machineutils/utils.go]: Consider
```go
// TriggerDeletionByMCM is the annotation set on the MachineDeployment by the CA-MCM cloud provider
// containing the machine names for which deletion should be triggered alongwith the time when 
// CA decided to scale-down those machines.
// Expected format for this annotation's value is [M1~T1,M2~T2,...]
```

File: pkg/controller/machineset.go [hunk 37]
```diff
@@ -889,3 +890,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+// that machine is added to the staleMachine list to be deleted.
+// This is done to have consistency between machineDeployment replica change and the machines marked for deletion.
+func getMachinesMarkedForDeletion(machineList []*v1alpha1.Machine, machineSet *v1alpha1.MachineSet) (staleMachines []*v1alpha1.Machine) {
+	machineSetLRCA, perr := time.Parse(time.RFC3339, machineSet.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime])
```
Comment (takoverflow) [inline pkg/controller/machineset.go:895]: nit: (Please ignore if you don't see the value)
If the machineSet object is only being used to check the `machineSetLRCA`, why not compute this value outside this function and pass just that rather than passing a pointer to the entire machine set. No point of calling it if `machineSetLRCA` cannot be parsed.

File: pkg/controller/deployment.go [hunk 38]
```diff
@@ -541,7 +550,13 @@ func (dc *controller) reconcileClusterMachineDeployment(key string) error {
 		return err
 	}
 
-	err = dc.setMachinePriorityAnnotationAndUpdateTriggeredForDeletion(ctx, d)
+	// Temporary code for backward compatibility, can be removed in later release
+	d, err = dc.adjustingMachineDeploymentAnnotations(ctx, d)
```
Comment (takoverflow) [inline pkg/controller/deployment.go]:
```suggestion
	d, err = dc.adjustMachineDeploymentDeletionAnnotation(ctx, d)
```

Nit

File: pkg/controller/deployment.go [hunk 39]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
-		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-		return err
+}
+
+func (dc *controller) adjustingMachineDeploymentAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (newMcd *v1alpha1.MachineDeployment, err error) {
+	mcdDeepCopy := mcd.DeepCopy()
+	if mcdDeepCopy.Annotations == nil {
+		mcdDeepCopy.Annotations = make(map[string]string)
+	}
+	if _, ok := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]; !ok {
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: Can this check be moved outside, so we check if the annotation isn't present, and then only call this function rather than calling it all the time.

File: pkg/controller/deployment.go [hunk 40]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = strings.Join(newTriggerDeletionAnnot, ",")
+		newMcd, err = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
+		if err != nil {
+			klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", newMcd.Name, len(newTriggerDeletionAnnot), newMcd.Annotations[machineutils.TriggerDeletionByMCM])
+			return nil, err
+		}
 	}
-	klog.V(3).Infof("Updated MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-	return nil
+	return newMcd, nil
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: This is a potential bug.

Returning `newMcd` which would be empty in case the annotation is already present, thus giving erroneous results for all the following functions in the caller.

File: pkg/controller/deployment.go [hunk 41]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		for _, machineName := range machineNames {
+			parts := strings.Split(machineName, "~")
+			if len(parts) == 1 {
+				newTriggerDeletionAnnot = append(newTriggerDeletionAnnot, fmt.Sprintf("%s~%s", parts[0], timestamp))
+			} else if len(parts) == 2 {
+				newTriggerDeletionAnnot = append(newTriggerDeletionAnnot, machineName)
+			}
+		}
+		mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = strings.Join(newTriggerDeletionAnnot, ",")
+		newMcd, err = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: Can it happen that during the time MCM is updating the mcd here, CA issued a scale-down and updated the same deployment as well, leading to this overriding CA's annotation or vice-versa.

Or is the expectation that there would be a conflict error in that case?

**Review by takoverflow — CHANGES_REQUESTED** [review]

File: pkg/controller/deployment.go [hunk 42]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		if err != nil {
+			klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", newMcd.Name, len(newTriggerDeletionAnnot), newMcd.Annotations[machineutils.TriggerDeletionByMCM])
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: When `err` is not `nil`, it could be that `newMcd` is `nil`. `mcdDeepCopy` could be used here instead to avoid panic.
This is especially true in the scenario @takoverflow mentioned, where near-concurrent updates can happen causing conflict error

File: pkg/controller/deployment.go [hunk 43]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+func (dc *controller) adjustingMachineDeploymentAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (newMcd *v1alpha1.MachineDeployment, err error) {
+	mcdDeepCopy := mcd.DeepCopy()
+	if mcdDeepCopy.Annotations == nil {
+		mcdDeepCopy.Annotations = make(map[string]string)
+	}
+	if _, ok := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]; !ok {
+		timestamp := time.Now().Format(time.RFC3339)
+		mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = timestamp
+		oldTriggerDeletionAnnot := mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM]
+		machineNames := strings.Split(oldTriggerDeletionAnnot, ",")
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: If `TriggerDeletionByMCM` is not present on the MCD, as `oldTriggerDeletionAnnot` would contain `""` due to it returning zero value, `machineNames` will be `[""]`. This can lead to malformed value (`~<Timestamp>` )on the MCD annotation

This could be fixed by not running this loop if the `TriggerDeletionByMCM` annotation is absent, like `LastDeploymentReplicaChangeByScalerTime` but with inverted condition.

File: pkg/controller/deployment.go [hunk 44]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+// computeMachineTriggerDeletionData computes the data related to machines that are triggered for deletion based on the annotation on the MachineDeployment.
+func (dc *controller) computeMachineTriggerDeletionData(mcd *v1alpha1.MachineDeployment) *triggerDeletionData {
+	oldTriggerDeletionAnnotationList := annotations.GetMachineNamesTriggeredForDeletion(mcd)
+	newTriggerDeletionAnnotationList := make([]string, 0)
+	machineMarkedDeletionTimes := make(map[*v1alpha1.Machine]string)
+
+	if len(oldTriggerDeletionAnnotationList) == 0 {
 		return nil
 	}
+	klog.Warningf("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(oldTriggerDeletionAnnotationList), oldTriggerDeletionAnnotationList)
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: Could be a `Infof`, as it runs unconditionally

File: pkg/controller/machineset.go [hunk 45]
```diff
@@ -419,44 +423,41 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
+
+	staleMachines = append(staleMachines, getMachinesMarkedForDeletion(machinesWithoutUpdateSuccessfulLabel, machineSet)...)
 
-		logMachinesWithPriority1(machinesWithoutUpdateSuccessfulLabel)
-		machinesToDelete := getMachinesToDelete(machinesWithoutUpdateSuccessfulLabel, machinesWithoutUpdateSuccessfulLabelDiff)
-		logMachinesToDelete(machinesToDelete)
+	for _, machine := range machinesWithoutUpdateSuccessfulLabel {
+		if machineutils.IsMachineFailed(machine) {
+			staleMachines = append(staleMachines, machine)
+			continue
```
Comment (gagan16k) [inline pkg/controller/machineset.go]: Nit: redundant, it is the last line of the loop anyways

File: pkg/controller/machineset.go [hunk 46]
```diff
@@ -419,44 +423,41 @@ func (c *controller) manageReplicas(ctx context.Context, allMachines []*v1alpha1
...
-		// but the ReplicaCount of newMachineSet has not increased yet.
-		// In such cases, we should not delete the machine immediately,
-		// otherwise it can cause unnecessary machine deletion and creation during in-place updates.
 		if machinesWithoutUpdateSuccessfulLabelDiff > BurstReplicas {
 			machinesWithoutUpdateSuccessfulLabelDiff = BurstReplicas
 		}
-		klog.V(2).Infof("Too many replicas for %v %s/%s, need %d, deleting %d", machineSet.Kind, machineSet.Namespace, machineSet.Name, (machineSet.Spec.Replicas), machinesWithoutUpdateSuccessfulLabelDiff)
+		logMachinesPriorityAndMarkedDeletionTime(machinesWithoutUpdateSuccessfulLabel)
+		staleMachines = append(staleMachines, getMachinesToDelete(machinesWithoutUpdateSuccessfulLabel, machinesWithoutUpdateSuccessfulLabelDiff)...)
+		logMachinesToDelete(staleMachines)
```
Comment (gagan16k) [inline pkg/controller/machineset.go]: This could be moved after `uniqueMachines()`, as the slice is incomplete at this stage

File: pkg/controller/machineset.go [hunk 47]
```diff
@@ -889,3 +890,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
 	return machine, retryErr
 }
+
+// getMachinesMarkedForDeletion iterates through the machines and if a machine has MarkedForDeletionTime before LastDeploymentReplicaChangeByScalerTime of the machineSet,
+// that machine is added to the staleMachine list to be deleted.
+// This is done to have consistency between machineDeployment replica change and the machines marked for deletion.
+func getMachinesMarkedForDeletion(machineList []*v1alpha1.Machine, machineSet *v1alpha1.MachineSet) (staleMachines []*v1alpha1.Machine) {
+	machineSetLRCA, perr := time.Parse(time.RFC3339, machineSet.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime])
+	if perr != nil {
+		klog.Warningf("Unable to parse %q of machineset %q: %v", machineutils.LastDeploymentReplicaChangeByScalerTime, machineSet.Name, machineSet)
```
Comment (gagan16k) [inline pkg/controller/machineset.go]:
```suggestion
		klog.Warningf("Unable to parse %q of machineset %q: %v", machineutils.LastDeploymentReplicaChangeByScalerTime, machineSet.Name, perr)
```

File: pkg/controller/machineset_test.go [hunk 48]
```diff
@@ -1813,4 +1812,133 @@ var _ = Describe("machineset", func() {
 			Expect(testMachineSet.Finalizers).To(Equal(finalizers))
 		})
 	})
+
+	Describe("#terminateMarkedMachines", func() {
```
Comment (gagan16k) [inline pkg/controller/machineset_test.go]: Might need to rename, as `terminateMarkedMachines()` does not exist

File: pkg/controller/controller_utils.go [hunk 49]
```diff
@@ -767,13 +767,22 @@ func (s ActiveMachines) Less(i, j int) bool {
...
 		return machineIPriority < machineJPriority
+	} else if s[i].Annotations[machineutils.MarkedForDeletionTime] != "" && s[j].Annotations[machineutils.MarkedForDeletionTime] == "" {
+		return true
+	} else if s[i].Annotations[machineutils.MarkedForDeletionTime] == "" && s[j].Annotations[machineutils.MarkedForDeletionTime] != "" {
+		return false
+	} else if s[i].Annotations[machineutils.MarkedForDeletionTime] != "" && s[j].Annotations[machineutils.MarkedForDeletionTime] != "" {
+		timeI, _ := time.Parse(time.RFC3339, s[i].Annotations[machineutils.MarkedForDeletionTime])
+		timeJ, _ := time.Parse(time.RFC3339, s[j].Annotations[machineutils.MarkedForDeletionTime])
+		// to have stable-sort where timeI <= timeJ
+		return !timeI.After(timeJ)
```
Comment (aaronfern) [inline pkg/controller/controller_utils.go]: In cases where `timeI == timeJ`, we should move further down and make a decision based on `Status.CurrentStatus.Phase` or `CreationTimestamp`

File: pkg/controller/machineset.go (hunk 37 above)
Comment (r4mek) [reply pkg/controller/machineset.go:895]: As the parent function is already too big, I would rather prefer not to make it more cluttered

File: pkg/controller/deployment.go (hunk 39 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: As the parent function is already too big, I would rather prefer not to make it more cluttered

File: pkg/controller/deployment.go (hunk 41 above)
Comment (takoverflow) [reply pkg/controller/deployment.go]: Discussed with @aaronfern offline, it's hard to avoid CA adding LRCBST if there's none and that leading to TDBMCM annotation having mix of machines with and without TS added. To alleviate this one time problem, we might end up running a script which fixes these broken annotations if any creep up during the one time update process.

File: pkg/controller/deployment.go [hunk 50]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		triggerDeletionAnnotationValue:        newTriggerDeletionAnnotationValue,
+		machineMarkedDeletionTimes:            machineMarkedDeletionTimes,
 	}
-	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdAdjust, metav1.UpdateOptions{})
-	if err != nil {
-		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-		return err
+}
+
+func (dc *controller) adjustingMachineDeploymentDeletionAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (newMcd *v1alpha1.MachineDeployment, err error) {
```
Comment (takoverflow) [inline pkg/controller/deployment.go]: `newMcd` is not being used anymore. Since you're always returning `mcdDeepCopy`.

File: pkg/controller/deployment.go (hunk 39 above)
Comment (takoverflow) [reply pkg/controller/deployment.go]: This is now needlessly making a mcd deepcopy every reconciliation when its only needed once.

But since this is a temporary function I don't want to split hairs too much. Resolving the comment.

File: pkg/controller/deployment.go [hunk 51]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+	mcdDeepCopy := mcd.DeepCopy()
+	if mcdDeepCopy.Annotations == nil {
+		mcdDeepCopy.Annotations = make(map[string]string)
+	}
+	if _, ok := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]; !ok {
```
Comment (takoverflow) [inline pkg/controller/deployment.go]:
```suggestion
    mcdDeepCopy := mcd.DeepCopy()
    if mcdDeepCopy.Annotations != nil && _, ok := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]; !ok {
```

If `mcdDeepCopy.Annotations` is nil i.e. there's nothing as part of `machineutils.TriggerDeletionByMCM` so there's no point in creating empty annotations map since we won't anyways be doing anything with it.

File: pkg/controller/deployment.go [hunk 52]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		timestamp := time.Now().Format(time.RFC3339)
+		mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = timestamp
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: Every MachineDeployment without `LastDeploymentReplicaChangeByScalerTime` gets it set to `time.Now()`, even those with no `TriggerDeletionByMCM` annotation.
Would this be acceptable behaviour?

Comment (takoverflow) [reply pkg/controller/deployment.go]: There's no harm done with that. Because there's no machines to compare this time for. And when CA issues scaledown, it will anyways update the LDRCBST.

File: pkg/controller/deployment.go (hunk 51 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: The code right now is such that if `mcd.Annotations == nil`, even then I am setting the `machineutils.LastDeploymentReplicaChangeByScalerTime` annotation. Do you want me to change that behaviour?

Comment (takoverflow) [reply pkg/controller/deployment.go]: But there's nothing to be gained by doing that right, because there aren't any machines that are triggered for deletion by scaler since there aren't any annotations. So adding this serves no purpose unless I am mistaken.

Comment (r4mek) [reply pkg/controller/deployment.go]: MB got confused by the code suggestion. You want the same thing as gagan's comment below, right?

File: pkg/controller/deployment.go (hunk 52 above)
Comment (gagan16k) [reply pkg/controller/deployment.go]: Yeah true, but we can also very easily avoid setting this annotation if not required by just extending the if condition below to include this and mcd `Update()` call.

File: pkg/controller/deployment.go [hunk 53]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		if err != nil {
+			klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(tgd.machineMarkedDeletionTimes), mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM])
+			return
+		}
+		klog.V(3).Infof("Updated MachineDeployment %q with #%d machines still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(tgd.machineMarkedDeletionTimes), mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM])
+	}
+
+	for machine, machineDeletionTime := range tgd.machineMarkedDeletionTimes {
+		if machine.Annotations[machineutils.MachinePriority] == "1" && machine.Annotations[machineutils.MarkedForDeletionTime] != "" {
+			klog.V(4).Infof("Machine %q of MachineDeployment %q already has MachinePriority=1 and MarkedForDeletionTime annotation", machine.Name, mcd.Name)
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]: It might be useful to log the MarkedForDeletionTime value that exists on the machine in this case.

File: pkg/controller/deployment.go [hunk 54]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+	klog.Warningf("MachineDeployment %q has #%d machine(s) marked for deletion, triggerForDeletionMachineNames=%v", mcd.Name, len(oldTriggerDeletionAnnotationList), oldTriggerDeletionAnnotationList)
 
-	triggerForDeletionMachineNames = sets.NewString(triggerForDeletionMachineNames...).Delete(skipTriggerForDeletionMachineNames...).List()
-	triggerDeletionAnnotValue := annotations.CreateMachinesTriggeredForDeletionAnnotValue(triggerForDeletionMachineNames)
+	for _, machineNameWithTime := range oldTriggerDeletionAnnotationList {
+		parts := strings.Split(machineNameWithTime, "~")
+		// We don't add the machine name with time that has invalid format into newTriggerDeletionAnnotationList to make sure that it is removed from the annotation
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if len(parts) != 2 {
+			klog.Infof("Invalid machine name with time format %q in MachineDeployment %q annotation, expected format is <machineName1>~<deletionTime1>,<machineName2>~<deletionTime2>... skip setting MachinePriority=1 annotation", machineNameWithTime, mcd.Name)
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]: I would recommend rewording this.

```suggestion
			klog.Infof("Invalid formatting in entry %q in MachineDeployment %q annotation value. Expected format is <machineName1>~<deletionTime1>,<machineName2>~<deletionTime2>; skipping setting MachinePriority=1 annotation", machineNameWithTime, mcd.Name)
```

File: pkg/controller/deployment.go [hunk 55]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+			continue
+		}
+		machineName, machineDeletionTime := parts[0], parts[1]
+		// We don't add the machine name with time that has invalid format into newTriggerDeletionAnnotationList to make sure that it is removed from the annotation
+		// and expect scaler to put the correct format in the annotation in the next retry.
+		if _, perr := time.Parse(time.RFC3339, machineDeletionTime); perr != nil {
+			klog.Warningf("Invalid deletion time format %q for machine %q in MachineDeployment %q annotation", machineDeletionTime, machineName, mcd.Name)
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]:
```suggestion
			klog.Warningf("Invalid formatting of deletion time %q for machine %q in MachineDeployment %q annotation", machineDeletionTime, machineName, mcd.Name)
```

File: pkg/controller/deployment.go [hunk 56]
```diff
@@ -642,60 +657,127 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		}
+		machine, gerr := dc.machineLister.Machines(dc.namespace).Get(machineName)
+		// The machine is deleted and hence we can remove it from the annotation.
+		if apierrors.IsNotFound(gerr) {
+			klog.V(4).Infof("Machine %q is not found in MachineDeployment %q - skip adding to newTriggerDeletionAnnotationList", machineName, mcd.Name)
+			continue
+		}
+		// The machine is in the process of being deleted hence we can remove it from the annotation and expect it to be deleted in the next retry.
+		if machineutils.IsMachineFailedOrTerminating(machine) {
+			klog.V(4).Infof("Machine %q of MachineDeployment %q is in Failed/Terminating state - skip adding to newTriggerDeletionAnnotationList", machineName, mcd.Name)
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]:
```suggestion
			klog.V(4).Infof("Machine %q of MachineDeployment %q is in Failed/Terminating state; skipping adding to newTriggerDeletionAnnotationList", machineName, mcd.Name)
```

File: pkg/controller/deployment.go [hunk 57]
```diff
@@ -642,60 +657,122 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		machineMarkedDeletionTimes:            machineMarkedDeletionTimes,
 	}
-	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdAdjust, metav1.UpdateOptions{})
-	if err != nil {
-		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-		return err
+}
+
+func (dc *controller) adjustingMachineDeploymentDeletionAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (mcdDeepCopy *v1alpha1.MachineDeployment, err error) {
+	mcdDeepCopy = mcd.DeepCopy()
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]: Can this not be moved to inside the if statement? That way you can avoid creating a deep copy unnecessarily.

File: pkg/controller/deployment.go [hunk 58]
```diff
@@ -642,60 +657,122 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+			if len(parts) == 1 {
+				newTriggerDeletionAnnotList = append(newTriggerDeletionAnnotList, fmt.Sprintf("%s~%s", parts[0], timestamp))
+			} else if len(parts) == 2 {
+				newTriggerDeletionAnnotList = append(newTriggerDeletionAnnotList, machineName)
+			}
+		}
+		mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = strings.Join(newTriggerDeletionAnnotList, ",")
+		_, err = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
+		if err != nil {
+			klog.Errorf("failed to update MachineDeployment %q, triggerDeletionAnnotValue=%q", mcdDeepCopy.Name, mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM])
```
Comment (thiyyakat) [inline pkg/controller/deployment.go]:
```suggestion
			klog.Errorf("failed to update MachineDeployment %q with annotation %q=%q", mcdDeepCopy.Name, machineutils.TriggerDeletionByMCM, mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM])
```

File: pkg/controller/deployment.go (hunk 52 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: I have done the requested changes.

File: pkg/controller/deployment_sync.go [hunk 59]
```diff
@@ -552,6 +553,9 @@ func (dc *controller) scaleMachineSet(ctx context.Context, is *v1alpha1.MachineS
 	var err error
 	if sizeNeedsUpdate || annotationsNeedUpdate {
 		isCopy.Spec.Replicas = newScale
+		if val, exists := deployment.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]; exists {
```
Comment (thiyyakat) [inline pkg/controller/deployment_sync.go]: if desired replicas on the MCD increase and decrease by 1 in quick succession, such that the desired replicas remains the same as the stale one on the machineSet, the update `isCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = val` will not be made right? Is that alright?

File: pkg/controller/machineset.go [hunk 60]
```diff
@@ -889,3 +887,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+		return
+	}
+
+	for _, machine := range machineList {
+		if machine.Annotations[machineutils.MarkedForDeletionTime] == "" || machine.Annotations[machineutils.MachinePriority] != "1" {
+			continue
+		}
+		machineLRCA, err := time.Parse(time.RFC3339, machine.Annotations[machineutils.MarkedForDeletionTime])
+		if err != nil {
+			klog.Infof("Error parsing time from %q with value %q of machine %q: %v", machineutils.MarkedForDeletionTime, machine.Annotations[machineutils.MarkedForDeletionTime], machine.Name, err)
```
Comment (thiyyakat) [inline pkg/controller/machineset.go]:
```suggestion
			klog.Infof("Error parsing time from annotation %q=%q on machine %q: %v", machineutils.MarkedForDeletionTime, machine.Annotations[machineutils.MarkedForDeletionTime], machine.Name, err)
```

File: pkg/controller/machineset.go [hunk 61]
```diff
@@ -889,3 +887,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+			continue
+		}
+		if machineLRCA.Before(machineSetLRCA) || machineLRCA.Equal(machineSetLRCA) {
+			staleMachines = append(staleMachines, machine)
+		}
+	}
+
```
Comment (thiyyakat) [inline pkg/controller/machineset.go:915]: Blank line can be removed.
```suggestion
```

File: pkg/controller/machineset.go [hunk 62]
```diff
@@ -889,3 +887,46 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+	return
+}
+
+// uniqueMachines returns the input slice with duplicates removed (by MachineKey),
+// preserving the first occurrence order.
+func uniqueMachines(machines []*v1alpha1.Machine) []*v1alpha1.Machine {
```
Comment (thiyyakat) [inline pkg/controller/machineset.go]: Consider moving this to `machineset_util.go`.

File: pkg/util/provider/machineutils/utils.go [hunk 63]
```diff
@@ -59,10 +59,18 @@ const (
 	// NotManagedByMCM annotation helps in identifying the nodes which are not handled by MCM
 	NotManagedByMCM = "node.machine.sapcloud.io/not-managed-by-mcm"
 
-	// TriggerDeletionByMCM can be set on the MachineDeployment and contains the machine names for which deletion should be triggered.
-	// This feature is leveraged by the CA-MCM cloud provider.
+	// TriggerDeletionByMCM when set on the MachineDeployment by the CA-MCM cloud provider contains the machine names
```
Comment (thiyyakat) [inline pkg/util/provider/machineutils/utils.go]:
```suggestion
	// TriggerDeletionByMCM is the annotation set on the MachineDeployment by the CA-MCM cloud provider. It contains the machine names
```

File: pkg/util/provider/machineutils/utils.go [hunk 64]
```diff
@@ -59,10 +59,18 @@ const (
...
+	// for which deletion should be triggered alongwith the time when CA decided to scale-down those machines.
```
Comment (thiyyakat) [inline pkg/util/provider/machineutils/utils.go]: Nit.
```suggestion
	// for which deletion should be triggered along with the time when CA decided to scale-down those machines.
```

File: pkg/controller/deployment.go (hunk 57 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: I am returning it back. Hence, don't want it to be `nil`

Comment (takoverflow) [reply pkg/controller/deployment.go]: This would've been avoided if the check was done outside the function.

Comment (r4mek) [reply pkg/controller/deployment.go]: Not really in favour of this. As the current implementation has 2 advantages:
 1. The code is cleaner as the parent function is not cluttered.
 2. It is easier to unit test the code.

Comment (gagan16k) [reply pkg/controller/deployment.go]: > I am returning it back. Hence, don't want it to be nil

Instead of named returns, this could directly return the argument when the main condition is not met, and the updated value when it is
``` go
if mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] == "" && mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] != "" {
		mcdDeepCopy = mcd.DeepCopy()
		......
		updatedMCD, updateErr = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
		if updateErr != nil {
			......
			return nil, updateErr
		}
		return updatedMCD, nil
	}
	return mcd, nil
```

We could just return an updated object instead of the same deepcopy which has been passed this way

File: pkg/controller/deployment.go [hunk 65]
```diff
@@ -642,60 +657,122 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
-			continue
+		mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = tgd.triggerDeletionAnnotationValue
+		if mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] == "" {
+			delete(mcdDeepCopy.Annotations, machineutils.TriggerDeletionByMCM)
 		}
-		if mc.Annotations[machineutils.MachinePriority] == "1" {
-			klog.V(4).Infof("Machine %q of MachineDeployment %q already marked with MachinePriority=1 annotation", machineName, mcd.Name)
+		_, err = dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
+		if err != nil {
+			klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(tgd.machineMarkedDeletionTimes), mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM])
```
Comment (gagan16k) [inline pkg/controller/deployment.go]:
```suggestion
			klog.Errorf("failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(tgd.machineMarkedDeletionTimes), machine.Annotations[machineutils.TriggerDeletionByMCM])
```

Comment (r4mek) [reply pkg/controller/deployment.go]: This is targeting the wrong line but I have fixed the problem

File: pkg/controller/deployment_sync.go [hunk 66]
```diff
@@ -547,11 +548,14 @@ func (dc *controller) scaleMachineSet(ctx context.Context, is *v1alpha1.MachineS
 	// call SetReplicasAnnotations inside the following if clause. Then we can also move the deep-copy from
 	// above inside the if too.
 	annotationsNeedUpdate := SetReplicasAnnotations(isCopy, (deployment.Spec.Replicas), (deployment.Spec.Replicas)+MaxSurge(*deployment))
+	// We keep the LDRCBST annotation of MCS always in sync with MCD, regardless of whether any replica change was observed.
+	LDRCBSTchanged := deployment.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] != is.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]
```
Comment (aaronfern) [inline pkg/controller/deployment_sync.go:552]: I don't understand why we would want to do this?
We need to update this timestamp only when we actually make a change to the replicas. Even of the timestamp does not match with what the mcd has, it should be updated until the change in replicas is also brought in as well

Comment (r4mek) [reply pkg/controller/deployment_sync.go:552]: Assume this scenario;
MCD Replicas = 5
At T1 -- CA scales down MCD and puts the annotation to delete M1
  MCD Replicas = 4
  MCD LDRCBST = T1
  MCD TDBMCM = M1\~T1
At T2 -- CA scales up MCD
  MCD Replicas = 5
  MCD LDRCBST = T1
  MCD TDBMCM = M1\~T1
  
Now if MCD starts tries to sync the annotation with the MCS, it won't put LDRCBST as there was no scaling observed.

CA won't consider M1 as scale-down candidate again since it will be present in the annotation MCD TDBMCM.

Comment (aaronfern) [reply pkg/controller/deployment_sync.go:552]: You are right, this is valid.
Thanks for explaining!

File: pkg/controller/deployment.go [hunk 67]
```diff
@@ -642,60 +657,129 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+func (dc *controller) adjustingMachineDeploymentDeletionAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (*v1alpha1.MachineDeployment, error) {
+	if mcd.Annotations[machineutils.TriggerDeletionByMCM] == "" {
+		return mcd, nil
+	}
+
+	mcdDeepCopy := mcd.DeepCopy()
+	if mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] == "" {
+		mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = time.Now().Format(time.RFC3339)
+	}
+	timestamp := mcd.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]
```
Comment (aaronfern) [inline pkg/controller/deployment.go]:
```suggestion
	timestamp := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]
```

I found this out during local testing. I think you meant to get this from the DeepCopy object but just missed it

Alternatively, you can also set `timestamp := time.Now().Format(time.RFC3339)` and use this variable throughout

File: pkg/controller/deployment.go [hunk 68]
```diff
@@ -642,60 +657,129 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		if len(parts) == 1 {
+			newTriggerDeletionAnnotList = append(newTriggerDeletionAnnotList, fmt.Sprintf("%s~%s", parts[0], timestamp))
+		} else if len(parts) == 2 {
+			newTriggerDeletionAnnotList = append(newTriggerDeletionAnnotList, machineName)
+		}
 	}
-	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdAdjust, metav1.UpdateOptions{})
+
+	mcdDeepCopy.Annotations[machineutils.TriggerDeletionByMCM] = strings.Join(newTriggerDeletionAnnotList, ",")
+	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdDeepCopy, metav1.UpdateOptions{})
```
Comment (gagan16k) [inline pkg/controller/deployment.go]: - Since Update() returns the latest state of the object, we can replace mcdDeepCopy with this returned version to ensure we are working with the most current data.
- Instead of unconditionally calling `Update()`, an inequality check could be performed on the current value of `TriggerDeletionByMCM` with the value of `Join(newTriggerDeletionAnnotList, ",")`

WDYT?

Comment (r4mek) [reply pkg/controller/deployment.go]: >Instead of unconditionally calling Update(), an inequality check could be performed on the current value of TriggerDeletionByMCM with the value of Join(newTriggerDeletionAnnotList, ",")

This can be done.

>Since Update() returns the latest state of the object, we can replace mcdDeepCopy with this returned version to ensure we are working with the most current data.

There was some discussion about this above. Also, it would be risky if we get updates to the MCD from some other cluster object.

File: pkg/controller/controller_utils.go [hunk 69]
```diff
@@ -767,13 +767,23 @@ func (s ActiveMachines) Less(i, j int) bool {
...
-	// Case-2: If both priorities are equal, then we look at their machinePhase
+	// Case-1: Initially we try to prioritize machine deletion based on machinePriority annotation.
+	// Case-2: If both priorities are equal, then we pick the one with older MarkedForDeletionTime annotation
+	// Case-3: If both don't have the MarkedForDeletionTime annotation, then we look at their machinePhase
 	// and prioritize as mentioned in the above map
-	// Case-3: If both Case-1 & Case-2 is false, we prioritize based on creation time
+	// Case-4: If all above cases are false, we prioritize based on creation time
 	if machineIPriority != machineJPriority {
 		return machineIPriority < machineJPriority
+	} else if s[i].Annotations[machineutils.MarkedForDeletionTime] != s[j].Annotations[machineutils.MarkedForDeletionTime] {
```
Comment (elankath) [inline pkg/controller/controller_utils.go:777]: avoid repeated map lookups - move to local variables `machineIDelTime`, `machineJDelTime`. Can do this later if you need to release ASAP.

File: pkg/controller/deployment.go [hunk 70]
```diff
@@ -642,60 +657,132 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		klog.V(3).Infof("Machine %q of MachineDeployment %q marked with MachinePriority=1 annotation successfully", machine.Name, mcd.Name)
 	}
 
-	if len(skipTriggerForDeletionMachineNames) == 0 {
+	return
+}
+
+// computeMachineTriggerDeletionData computes the data related to machines that are triggered for deletion based on the annotation on the MachineDeployment.
+func (dc *controller) computeMachineTriggerDeletionData(mcd *v1alpha1.MachineDeployment) *triggerDeletionData {
+	oldTriggerDeletionAnnotationList := annotations.GetMachineNamesTriggeredForDeletion(mcd)
```
Comment (elankath) [inline pkg/controller/deployment.go:710]: `annotations.GetMachineNamesTriggeredForDeletion` is invalid name now and misleading, I suggest changing this to `annotation.GetMachineNamesAndDeletionTimes(*MachineDeploment) map[string]time.Time`.  Let the split happen inside this function. Or alternatively, remove this function altogether.

File: pkg/controller/deployment.go [hunk 71]
```diff
@@ -642,60 +657,132 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
-		klog.V(3).Infof("Machine %q of MachineDeployment %q marked with MachinePriority=1 annotation successfully", machineName, mcd.Name)
+		klog.V(3).Infof("Machine %q of MachineDeployment %q marked with MachinePriority=1 annotation successfully", machine.Name, mcd.Name)
 	}
 
-	if len(skipTriggerForDeletionMachineNames) == 0 {
+	return
+}
+
+// computeMachineTriggerDeletionData computes the data related to machines that are triggered for deletion based on the annotation on the MachineDeployment.
+func (dc *controller) computeMachineTriggerDeletionData(mcd *v1alpha1.MachineDeployment) *triggerDeletionData {
```
Comment (elankath) [inline pkg/controller/deployment.go:709]: Do not return pointer. Return struct instance and remove `nil` check from caller.

File: pkg/controller/deployment.go (hunk 68 above)
Comment (gagan16k) [reply pkg/controller/deployment.go]: From discussion with @r4mek:

In the current code:
Suppose you have a MCD with some replica count at the start

T1:  mcd update at `adjustingMachineDeploymentDeletionAnnotations()` happens
- If MCD replicas have changed by any other actor, then this update fails due to a change in `resourceVersion` vs what the deepcopy has, and this forces a retry
- If not, update succeeds, and the old deep copy is passed to `updateMachineAndMachineDeploymentDeletionAnnotations()`

 T2: `updateMachineAndMachineDeploymentDeletionAnnotations()` runs
- Assume MCD replicas are changed before an update, then it fails as the `resourceVersion` is stale.
- If not, the update still fails, because now the annotations have been updated. This can be avoided if we pass the latest mcd deepcopy from the annotation update at `adjustingMachineDeploymentDeletionAnnotations()`

Any opinions @aaronfern, @elankath, @takoverflow, @thiyyakat?

File: pkg/controller/deployment.go [hunk 72]
```diff
@@ -46,6 +47,14 @@ import (
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/machineutils"
 )
 
+// triggerDeletionData contains the annotation to be put on machineDeployment, a boolean to indicate whether annotation is changed and
+// map of machine and its markedDeletionTime
+type triggerDeletionData struct {
+	machineMarkedDeletionTimes            map[*v1alpha1.Machine]string
```
Comment (elankath) [inline pkg/controller/deployment.go]: Prefer using 2 slices `machines` and `machineDeletionTimes` instead of a `map[*v1alpha1.Machine]` here. A map is meant for lookup and pointers to cache invalid-table k8s objects are not good for lookup.  But you can do this later if in a hurry.

Comment (takoverflow) [reply pkg/controller/deployment.go]: Having two separate slices won't help since you need a mapping from the machineName to its marked deletion time. So wouldn't a `map[string]string` would be better?

File: pkg/controller/deployment.go [hunk 73]
```diff
@@ -642,60 +657,132 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		return mcd, nil
 	}
-	klog.V(3).Infof("Updated MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-	return nil
+
+	mcdDeepCopy := mcd.DeepCopy()
+	if mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] == "" {
+		mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime] = time.Now().Format(time.RFC3339)
+	}
+	timestamp := mcdDeepCopy.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime]
```
Comment (elankath) [inline pkg/controller/deployment.go:767]: Move this variable above and call it `replicaChangeTimestamp`, so you don't need to look it up in map 3 times.

File: pkg/controller/deployment.go [hunk 74]
```diff
@@ -642,60 +657,132 @@ func (dc *controller) updateMachineDeploymentFinalizers(ctx context.Context, mac
...
+		triggerDeletionAnnotationValue:        newTriggerDeletionAnnotationValue,
+		machineMarkedDeletionTimes:            machineMarkedDeletionTimes,
 	}
-	_, err := dc.controlMachineClient.MachineDeployments(mcd.Namespace).Update(ctx, mcdAdjust, metav1.UpdateOptions{})
-	if err != nil {
-		klog.Errorf("Failed to update MachineDeployment %q with #%d machine names still pending deletion, triggerDeletionAnnotValue=%q", mcd.Name, len(triggerForDeletionMachineNames), triggerDeletionAnnotValue)
-		return err
+}
+
+func (dc *controller) adjustingMachineDeploymentDeletionAnnotations(ctx context.Context, mcd *v1alpha1.MachineDeployment) (*v1alpha1.MachineDeployment, error) {
```
Comment (elankath) [inline pkg/controller/deployment.go:758]: Keep a note for later: Move the computation of new annotation to separate function so it takes old annotation value and returns new annotation value. This allows unit-testing with no updation code.

File: pkg/controller/deployment.go (hunk 71 above)
Comment (r4mek) [reply pkg/controller/deployment.go:709]: Wouldn't this be efficient in terms of memory?

File: pkg/controller/deployment.go (hunk 72 above)
Comment (r4mek) [reply pkg/controller/deployment.go]: We can use the index for lookup. `machine[i]` has its corresponding deletion time as `delTime[i]`.

Comment (takoverflow) [reply pkg/controller/deployment.go]: Separating two related objects that should be meaningfully grouped together isn't clean imo, your call.

File: pkg/controller/deployment.go (hunk 73 above)
Comment (r4mek) [reply pkg/controller/deployment.go:767]: I am putting this timestamp on machines which were in old format `[M1,M2,...]`. If the MCD has `LastDeploymentReplicaChangeByScalerTime` then I will be just copying it, else I will be setting `LastDeploymentReplicaChangeByScalerTime` to `time.Now()` and putting this same time on machines.

File: pkg/controller/deployment.go (hunk 70 above)
Comment (r4mek) [reply pkg/controller/deployment.go:710]: Here the annotation could be in old format `[M1,M2,...]`

File: pkg/controller/machineset.go [hunk 75]
```diff
@@ -889,3 +887,30 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+// This is done to have consistency between machineDeployment replica change and the machines marked for deletion.
+func getMachinesMarkedForDeletion(machineList []*v1alpha1.Machine, machineSet *v1alpha1.MachineSet) (staleMachines []*v1alpha1.Machine) {
+	machineSetLRCA, perr := time.Parse(time.RFC3339, machineSet.Annotations[machineutils.LastDeploymentReplicaChangeByScalerTime])
+	if perr != nil {
+		klog.Warningf("Unable to parse %q of machineset %q: %v", machineutils.LastDeploymentReplicaChangeByScalerTime, machineSet.Name, perr)
+		return
+	}
+
+	for _, machine := range machineList {
+		if machine.Annotations[machineutils.MarkedForDeletionTime] == "" || machine.Annotations[machineutils.MachinePriority] != "1" {
```
Comment (elankath) [inline pkg/controller/machineset.go]: assign to local variable `markForDelTime` instead of repeated map lookups.

File: pkg/controller/deployment.go (hunk 68 above)
Comment (aaronfern) [reply pkg/controller/deployment.go]: Fair enough
The Update() call in `adjustingMachineDeploymentDeletionAnnotations()` returns the updated `mcd` (which right now is discarded). This can be passed back

Although, it's highly unlikely that we would have to update mcd in `adjustingMachineDeploymentDeletionAnnotations()` followed by `updateMachineAndMachineDeploymentDeletionAnnotations()` in succession, so if the effort in addressing this is a bit much, I would not try to solve this. Worst case we'll have an error and retry

File: pkg/controller/controller_utils.go [hunk 76]
```diff
@@ -767,13 +767,24 @@ func (s ActiveMachines) Less(i, j int) bool {
...
+		machineIDeletionTime, machineJDeletionTime := s[i].Annotations[machineutils.MarkedForDeletionTime], s[j].Annotations[machineutils.MarkedForDeletionTime]
+		if machineIDeletionTime != "" && machineJDeletionTime == "" {
+			return true
+		} else if machineIDeletionTime == "" && machineJDeletionTime != "" {
+			return false
+		} else {
+			timeI, _ := time.Parse(time.RFC3339, machineIDeletionTime)
```
Comment (takoverflow) [inline pkg/controller/controller_utils.go:785]: Ignoring these errors might be problematic. Consider the case with corrupted timestring so its non-empty

```go
	eTime, err := time.Parse(time.RFC3339, "xyz")
	fmt.Printf("Error time parse: %v\nErr: %v\n", eTime, err)
```

Gives the time value as `0001-01-01 00:00:00 +0000 UTC` value which will always be before any sane timestamp.
```
Error time parse: 0001-01-01 00:00:00 +0000 UTC
Err: parsing time "xyz" as "2006-01-02T15:04:05Z07:00": cannot parse "xyz" as "2006"
```

File: pkg/controller/deployment.go [hunk 77]
```diff
@@ -46,6 +47,15 @@ import (
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/machineutils"
 )
 
+// triggerDeletionData contains the annotation to be put on machineDeployment, a boolean to indicate whether annotation is changed and
+// map of machine and its markedDeletionTime
```
Comment (takoverflow) [inline pkg/controller/deployment.go:51]: TODO: For later, please update the docstring since it still refers to the older definition of the struct

File: pkg/controller/machineset.go [hunk 78]
```diff
@@ -889,3 +887,31 @@ func UpdateMachineWithRetries(ctx context.Context, machineClient v1alpha1client.
...
+		klog.Warningf("Unable to parse %q of machineset %q: %v", machineutils.LastDeploymentReplicaChangeByScalerTime, machineSet.Name, perr)
+		return
+	}
+
+	for _, machine := range machineList {
+		markedMachineDeletionTime := machine.Annotations[machineutils.MarkedForDeletionTime]
+		if markedMachineDeletionTime == "" || machine.Annotations[machineutils.MachinePriority] != "1" {
+			continue
+		}
+		machineLRCA, err := time.Parse(time.RFC3339, markedMachineDeletionTime)
```
Comment (gagan16k) [inline pkg/controller/machineset.go:906]: Another TODO for later: This variable name might be outdated
