### PR TITLE
Avoid the deletion of the machines in CrashLoopBackoff state by the safety controller

### LINKED ISSUE #583: Race condition while creating machines in CrashLoopBackoff state
**What happened**:
The orphan controller always used to ignore machines that are being just in creation. I.e that `status.CurrentStatus.Phase` was not set. However, with the introduction of `CrashLoopBackOff`, and when the first try for machine creation fails and any further retries lead to the possibility of VMs showing up on the consoled prior to updating the machine object and hence is treated as an orphan VM. This is causing this race to lead to this state.
Refer - [machine safety code](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machine_safety.go#L575-L580)

**What you expected to happen**:
For the VM to be not treated as an orphan and allow it to join.  

**How to reproduce it (as minimally and precisely as possible)**:

Try creating a VM that should return an error on the first creation and post which the next creations should lead to this race condition on providers that return after too long. 

**Anything else we need to know**:

One way I think of fixing this would be to ignore machines in crashLoopBackoff while trying to clean up orphan machines. 

Sample MCM logs
```
I1215 14:55:12.856005       1 controller_utils.go:599] Controller shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994 created machine shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk
I1215 14:55:12.856529       1 event.go:255] Event(v1.ObjectReference{Kind:"MachineSet", Namespace:"shoot--garden--ccee-m3-eu1", Name:"shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994", UID:"94661b5e-2fac-4006-bc36-6df5a2e0a42b", APIVersion:"machine.sapcloud.io/v1alpha1", ResourceVersion:"463618256", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created Machine: shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk
I1215 14:55:12.873818       1 machine.go:421] Creating machine "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk", please wait!
I1215 14:58:52.954724       1 machine_safety.go:571] SafetyController: Machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" is being processed by machine controller, hence skipping
I1215 14:59:14.850510       1 machine_safety.go:571] SafetyController: Machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" is being processed by machine controller, hence skipping
I1215 15:01:38.556883       1 machine_safety.go:571] SafetyController: Machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" is being processed by machine controller, hence skipping
I1215 15:02:11.576825       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
E1215 15:02:15.491244       1 machine.go:478] Error while creating machine shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk: error waiting for the "566dfa8a-088c-480f-a9b3-e8df2f32a8ed" server status: unexpected status "ERROR", wanted target "ACTIVE", fault: {Code:0 Created:0001-01-01 00:00:00 +0000 UTC Details: Message:}
I1215 15:02:15.526334       1 machine.go:421] Creating machine "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk", please wait!
I1215 15:02:25.048400       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:02:26.654552       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:02:28.529091       1 machine_safety.go:639] SafetyController: Orphan VM found and terminated VM: shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk, openstack:///eu-nl-1/90e0b27a-fe40-43b9-b6ac-ff2e7cc24c21
E1215 15:03:16.153424       1 machine.go:478] Error while creating machine shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk: error waiting for the "90e0b27a-fe40-43b9-b6ac-ff2e7cc24c21" server status: Resource not found
I1215 15:03:16.158002       1 machine.go:843] Not updating the status of the machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" , as it is already same
I1215 15:04:15.526510       1 machine.go:421] Creating machine "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk", please wait!
I1215 15:11:34.552966       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:11:37.942393       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:11:39.342763       1 machine_safety.go:639] SafetyController: Orphan VM found and terminated VM: shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk, openstack:///eu-nl-1/8cdfe48d-8f0f-4a9c-ae06-cdcb20dca785
E1215 15:11:41.647753       1 machine.go:478] Error while creating machine shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk: error waiting for the "8cdfe48d-8f0f-4a9c-ae06-cdcb20dca785" server status: Resource not found
I1215 15:11:41.651507       1 machine.go:843] Not updating the status of the machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" , as it is already same
I1215 15:13:41.657137       1 machine.go:421] Creating machine "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk", please wait!
I1215 15:14:38.246596       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:14:39.841766       1 driver_openstack.go:417] Found machine with name: "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk"
I1215 15:14:41.534624       1 machine_safety.go:639] SafetyController: Orphan VM found and terminated VM: shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk, openstack:///eu-nl-1/6e56cc76-5e62-4a32-a099-f233681fe4ba
E1215 15:14:43.053013       1 machine.go:478] Error while creating machine shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk: error waiting for the "6e56cc76-5e62-4a32-a099-f233681fe4ba" server status: Resource not found
I1215 15:14:43.057342       1 machine.go:843] Not updating the status of the machine object "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk" , as it is already same
I1215 15:16:43.064546       1 machine.go:421] Creating machine "shoot--garden--ccee-m3-eu1-cpu-worker-z1-85994-s9kpk", please wait!
```

**Environment**:
/platform openStack
/platform azure 
(i think, this could affect these platforms as they take longer to return on a create call)

cc: @vpnachev

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**What this PR does / why we need it**:
This PR will avoid the deletion of the machines in CrashLoopBackoff state by the safety controller

**Which issue(s) this PR fixes**:
Fixes #583 

**Special notes for your reviewer**:
More UTs shall be added to test this scenario in the near future. This one is an immediate solution to mitigate the issue.

**Release note**:

```other operator
Avoid the deletion of the machines in CrashLoopBackoff state by the safety controller
```

### CODE REVIEW

**Comment by prashanth26** [comment]
Hi @AxiomSamarth ,

We would also need this fix and test on the OOT code path here - https://github.com/gardener/machine-controller-manager/blob/master/pkg/util/provider/machinecontroller/machine_safety.go#L222.

**Comment by AxiomSamarth** [comment]
Sure, @prashanth26 I will make the changes and update the PR. Thank you :)

**Comment by AxiomSamarth** [comment]
@amshuman-kr @prashanth26 For writing this UT, I had to introduce a new method Add() in the driver interface. Should it be retained or now that we understand how to handle the scenario, should we remove the Add() method from the interface and of course driver implementations?

**Comment by amshuman-kr** [comment]
@AxiomSamarth Thanks for the unit test! 

> @amshuman-kr @prashanth26 For writing this UT, I had to introduce a new method Add() in the driver interface. Should it be retained or now that we understand how to handle the scenario, should we remove the Add() method from the interface and of course driver implementations?

I don't think it is a good idea to enhance the `Driver` interface for a functionality that is only used in the unit tests. That leads to nop implementations in _proper_ drivers which is not desirable.

You can enhance just the `FakeDriver` to have an additional `add` function field and also make it implement an `Add` function which delegates to the `add` function field (but without adding the `Add` function to the `Driver` interface). You can also enhance the `NewFakeDriver` to take the additional function parameter. Then in the unit tests you can typecast the `Driver` instance returned by the `NewFakeDriver` to the `FakeDriver` struct type and call the `Add` function. This way you get the feature needed by the unit tests without disturbing other `Driver` implementations.

> I also see a similar thing to do in the out of tree code as well. I will have to add a new method in the interface. Am I doing it correctly or is there a different approach?

You can use pretty much the same approach as I mentioned above here as well. Or you can chose even generate mocks for the OOT interface and simulate the responses that way. I am fine either way.

**Comment by amshuman-kr** [comment]
>You can use pretty much the same approach as I mentioned above for OOT as well. Or you can chose to even generate mocks for the OOT interface and simulate the responses that way. I am fine either way.

I think the mock approach is more suitable for OOT.

**Comment by AxiomSamarth** [comment]
The recommended changes are made and pushed to this PR branch.

- The Driver Interface is restored to as it was before.
- FakeDriver struct implements the necessary methods for the unit tests for both in-tree and out-of-tree.
- The proposed logic by @prashanth26 to avoid the machines from being deleted by the safety controller is also included in this for both in-tree and out-of-tree safety controller code.

Looking forward for review comments/suggestions.

File: pkg/util/provider/driver/fake.go [hunk 1]
```diff
@@ -25,6 +25,11 @@ import (
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/machinecodes/status"
 )
 
+// VMs ...
+type VMs map[string]string
+
+var fakeVMs = make(VMs)
```
Comment (amshuman-kr) [inline pkg/util/provider/driver/fake.go:31]: Can you please move the fakeVMs as a private field in the `FakeDriver` struct? This is possible in the OoT case this is possible because the driver is passed ot the controller instead of constructed by the controller.

**Review by amshuman-kr — CHANGES_REQUESTED** [review]
LGTM except for a small suggestion to move the `fakeVMs` as a private field in the `FakeDriver` struct for the OoT case.

File: pkg/util/provider/driver/fake.go [hunk 2]
```diff
@@ -25,20 +25,31 @@ import (
...
 	VMExists       bool
 	ProviderID     string
 	NodeName       string
 	LastKnownState string
 	Err            error
+	fakeVMs        VMs
 }
 
 // NewFakeDriver returns a new fakedriver object
 func NewFakeDriver(fakeDriver *FakeDriver) Driver {
```
Comment (amshuman-kr) [inline pkg/util/provider/driver/fake.go:42]: Should't we create a new struct instance here? Otherwise what is the point of this func?

File: pkg/util/provider/driver/fake.go [hunk 3]
```diff
@@ -25,20 +25,31 @@ import (
...
 	return fakeDriver
 }
 
+// AddMachine makes a call to the driver to create the machine.
+func (d *FakeDriver) AddMachine() error {
+	d.fakeVMs = make(VMs)
```
Comment (amshuman-kr) [inline pkg/util/provider/driver/fake.go:48]: This is incorrect. The array has to be initialized during construction of the struct instance.

File: pkg/util/provider/machinecontroller/ms_test.go [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+						Phase: v1alpha1.MachineRunning,
+					},
+				},
+			}
+
+			controlMachineObjects := []runtime.Object{}
+			controlMachineObjects = append(controlMachineObjects, testMachineObject1)
+			controlMachineObjects = append(controlMachineObjects, testMachineObject2)
+
+			fakeDriver := driver.NewFakeDriver(&driver.FakeDriver{
```
Comment (amshuman-kr) [inline pkg/util/provider/machinecontroller/ms_test.go:106]: Please move the instance construction inside the `NewFakeDriver` func. The func can take what parameters are required.

**Review by amshuman-kr — CHANGES_REQUESTED** [review]
Please move the instance construction inside the `NewFakeDriver` func. The func can take what parameters are required.

File: pkg/util/provider/driver/fake.go (hunk 2 above)
Comment (AxiomSamarth) [reply pkg/util/provider/driver/fake.go:42]: Yes, Amshu. Creating a new instance according to the params passed to it, definitely makes more sense considering the func `NewFakeDriver` exists. I will do the changes.

File: pkg/util/provider/driver/fake.go (hunk 3 above)
Comment (AxiomSamarth) [reply pkg/util/provider/driver/fake.go:48]: Understood!

File: pkg/util/provider/machinecontroller/ms_test.go (hunk 4 above)
Comment (AxiomSamarth) [reply pkg/util/provider/machinecontroller/ms_test.go:106]: Yes, Amshu. I got your point fully now. Changes on the way!

**Comment by AxiomSamarth** [comment]
Hi Amshu,

I have not really made changes to the structure of the `FakeDriver` struct. Probably, because I could not think of any better way. However, I have modified the `AddMachine` method and also employed this `AddMachine` method in the `NewFakeDriver` struct to support handling multiple `fakeVMs`.

Also, with this change, I could add multiple fakeVMs and see through the test results that the machine in `crashloopBackOff` state remains from deletion while the other test machine in `running` state gets deleted.

**Review by amshuman-kr — APPROVED** [review]
Thanks for the changes. LGTM :-)

File: pkg/controller/ms_test.go [hunk 5]
```diff
@@ -0,0 +1,134 @@
+/*
```
Comment (prashanth26) [inline pkg/controller/ms_test.go:1]: Can we move these tests to `machine_safety_test.go` file? As usually tests for a particular file are to be maintained in the `*_test.go` file for consistency.

File: pkg/util/provider/machinecontroller/ms_test.go [hunk 6]
```diff
@@ -0,0 +1,134 @@
+/*
```
Comment (prashanth26) [inline pkg/util/provider/machinecontroller/ms_test.go:1]: Same as above.

Can we move these tests to `machine_safety_test.go` file? As usually tests for a particular file are to be maintained in the `*_test.go` file for consistency.

**Review by prashanth26 — COMMENTED** [review]
Overall looks good. Just a minor change. Also, squash all the commits once you are done.

File: pkg/controller/ms_test.go (hunk 5 above)
Comment (AxiomSamarth) [reply pkg/controller/ms_test.go:1]: Sure, Prashanth. I will move the file content to `machine_safety_test.go` in both In-Tree and OOT.

**Review by prashanth26 — APPROVED** [review]
/lgtm

**Comment by prashanth26** [comment]
This fix should also resolve https://github.com/gardener/machine-controller-manager/issues/544 according to colleagues from MS.
