### PR TITLE
dont skip drain for unhealthy nodes

### LINKED ISSUE #781: Force Drain and detachment for Volumes for Unhealthy Nodes which were `NotReady` for over 5min
**How to categorize this issue?**

/area performance
/kind bug
/priority 2

**What happened**:

Currently we skip drain for an unhealthy node which we want to remove, if we see that it was not Ready for >5 min.
We have now seen problems with this. Imagine a node with a lot of PVs attached. Now node goes unhealthy and we skip drain, and start deleting the VM. 
In azure as part of deletion we currently detach the volumes from the VM (PV disks and root disk) and then proceed with VM deletion.
This means MCM now will detach the backing disks of the PVs for the pods directly and then trigger node deletion. K8s starts acting only after node deletion as till now everything was happening on infra.
KCM deletes the nodes, and then the orphan pod force deletion logic removes the pods. This only makes the attach/detach controller come into action.
The attach/detach controller relies on kubelet to direct CSI driver on the node to unmount the disk. Since there is no node , meaning no kubelet , the A/D controller waits till `maxWaitForUnmountDuration` (6min , non-configurable) and then only force detachment starts.

So there are two detachments , one by MCM and then by A/D controller. This leads to downtimes for the customers.

**What you expected to happen**:

Expect the pods with PV to recover faster after unhealthy nodes are removed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

During normal draining a wait for detachment and wait for reattachment( wait for new volumeattachment formation in case volumeattachment support is enabled) is done , introduced in https://github.com/gardener/machine-controller-manager/pull/608

live issue # 3645

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by elankath**
**What this PR does / why we need it**:
See #781
- Skipping drain for un-healthy nodes causes volume attachments to still be associated with old node.
- attach/detach controller in KCM takes `maxWaitForUnmountDuration` (6m) to expire attached volumes.
- After performing force drain, we also need to explicitly delete volume attachments for the old node. This prevents triggering `maxWaitForUnmountDuration` from taking affect and volumes are attached to replacement node (if any).

**Which issue(s) this PR fixes**:
Fixes #781

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Force drain and delete volume attachments for nodes un-healthy due to `ReadOnlyFileSystem` and `NotReady` for too long
```

### CODE REVIEW

**Comment by elankath** [comment]
## Test Scenario
1. Apply Deployment with several replicas and volumes
1. Crash Kubelet for a node using `systemctl stop kubelet`
1. Wait till Old Node becomes `NotReady`
1. Wait till old machine becomes `Terminating`
1. Wait till new machine is launched by MCM
1. Wait till new Machine is `Running` and new Node is `Ready`
1. Wait till Pods are `Running` on new node.
1. Measure time taken from old node `NotReady` to Pods `Running` on new node.
1. Check KCM Log to see presence of `maxWaitForUnmountDuration` timeout 

## Observations

### Situation Before Fix
```
21:22 -> crash kubelet
21:25 -> node become NotReady
21:35 -> old node becomes terminating, new node hvcf6 launches
21:39 -> new node becomes Running
21:39-> new pods scheduled ContainerCreating on new node
...unfortunately volume attachments are still associated with old node 7rrtb for several minutes. this node is no longer there. it has been terminated
I0809 21:44:02.428680       1 reconciler.go:274] "attacherDetacher.DetachVolume started: this volume is not safe to detach, but maxWaitForUnmountDuration expired, force detaching" duration="6m0s" volume={AttachedVolume:{VolumeName:kubernetes.io/csi/disk.csi.azure.com^/subscriptions/82b44c79-a5d4-4d74-8ff8-8639e79c1c39/resourceGroups/shoot--i034796--trea/providers/Microsoft.Compute/disks/pv-shoot--i034796--trea-92d86bf3-491f-4fda-bfe5-9846e5ca80ad VolumeSpec:0xc00396f098 NodeName:shoot--i034796--trea-trea-z1-66866-7rrtb PluginIsAttachable:true DevicePath: DeviceMountPath: PluginName: SELinuxMountContext:} MountedByNode:true DetachRequestedTime:2023-08-09 21:38:02.358419312 +0000 UTC m=+8110.954960133}
21:43-> new pods are in Running. new volumes associated with  7rrtb 
```
Time Taken ~ 21 mins

### Situation After Fix

```
06:04 -> crashed kubelet
06:07 -> hvcf6 became not ready, machine becomes Unknown
06:14 -> machine terminating
06:15-> new machine launched
06:17 -> pods in ContainerCreating
06:18 -> x78h7 becomes Running 
06:19 -> pods become Running

There is NO maxWaitForUnmountDuration in KCM log
```
Time Taken ~ 15 mins.

As can be seen there is an improvement of ~6 minutes.

**Comment by elankath** [comment]
All review comments addressed

- [x] Fix text of stage `DelVolumesAttachments`
- [x] Add an FAQ question:  "How does MCM handle an un-healthy node ?" in the *Internals* section.
- [x] Undo change for constant in `now := metav1.Now()`  while doing machineStatusUpdate.
- [x] Change text to `deleteNodeVolAttachments deletes VolumeAttachment(s) for a node and waits tillvolumes are detached from the node or detach timeout exceeded` . Remove reference to `wait`.
- [x]  Log the joined error returned from `deleteVolumeAttachmentsForNode`
- [x]  Log after deleting volume attachments.

**Comment by elankath** [comment]
## Re-tested after all review changes

### kubelet killed at  Thu Sep 21 09:07:34 UTC 2023

#### Poll Deployments,Pods,VolumeAttachments,Nodes at UTC Time: Thu Sep 21 09:10:37 UTC 2023, Local Time: Thu Sep 21 09:10:37 UTC 2023
```
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
deployment.apps/vol-test-a   0/4     4            0           46m   ubuntu       ubuntu   app=vol-test-a

NAME                              READY   STATUS    RESTARTS   AGE   IP           NODE                                   NOMINATED NODE   READINESS GATES
pod/vol-test-a-55bbbb77b6-4fwtx   1/1     Running   0          29m   10.180.0.5   shoot--i034796--az1-a-z1-85cf5-m9rfx   <none>           <none>
pod/vol-test-a-55bbbb77b6-6sbn9   1/1     Running   0          29m   10.180.0.5   shoot--i034796--az1-a-z1-85cf5-m9rfx   <none>           <none>
pod/vol-test-a-55bbbb77b6-7kgdw   1/1     Running   0          29m   10.180.0.5   shoot--i034796--az1-a-z1-85cf5-m9rfx   <none>           <none>
pod/vol-test-a-55bbbb77b6-sg8gs   1/1     Running   0          29m   10.180.0.5   shoot--i034796--az1-a-z1-85cf5-m9rfx   <none>           <none>

NAME                                                                                                   ATTACHER             PV                                                            NODE                                   ATTACHED   AGE
volumeattachment.storage.k8s.io/csi-08af6e9b391c406a84fe1206590764fb6076e0b657b47d9a2dc14b18c39bf2c7   disk.csi.azure.com   pv-shoot--i034796--az1-4f4b7484-3029-4603-8806-dcaad8c1da2b   shoot--i034796--az1-a-z1-85cf5-m9rfx   true       13m
volumeattachment.storage.k8s.io/csi-5615adc7d535b4b91cce4421a32a09d52b46111099c7d15188b033c8379227f5   disk.csi.azure.com   pv-shoot--i034796--az1-dba037bb-eb4b-45c0-85bf-87e19b8977c0   shoot--i034796--az1-a-z1-85cf5-m9rfx   true       13m
volumeattachment.storage.k8s.io/csi-585bf1aa7caf08a2686aa04ca4fcb7827e46a4520bb978983a638416b2957680   disk.csi.azure.com   pv-shoot--i034796--az1-040457ee-eaac-4b01-b690-92a814a91788   shoot--i034796--az1-a-z1-85cf5-m9rfx   true       13m
volumeattachment.storage.k8s.io/csi-99c05671376884fd7dc6663ba0a118195ae5b118a22c7991dd7e7785b6b16e11   disk.csi.azure.com   pv-shoot--i034796--az1-fcae9b4f-28b1-4483-aaf0-00a71f368b32   shoot--i034796--az1-a-z1-85cf5-m9rfx   true       13m
NAME                                   STATUS     ROLES    AGE    VERSION
shoot--i034796--az1-a-z1-85cf5-djz2j   Ready      <none>   19m    v1.26.7
shoot--i034796--az1-a-z1-85cf5-m9rfx   NotReady   <none>   121m   v1.26.7
```

#### Poll Deployments,Pods,VolumeAttachments,Nodes at UTC Time: Thu Sep 21 09:16:39 UTC 2023, Local Time: Thu Sep 21 09:16:39 UTC 2023

```
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
deployment.apps/vol-test-a   0/4     4            0           52m   ubuntu       ubuntu   app=vol-test-a

NAME                              READY   STATUS              RESTARTS   AGE    IP           NODE                                   NOMINATED NODE   READINESS GATES
pod/vol-test-a-55bbbb77b6-dmk8n   0/1     ContainerCreating   0          118s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-fkn7k   0/1     ContainerCreating   0          118s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-mc52s   0/1     ContainerCreating   0          118s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-wnnhg   0/1     ContainerCreating   0          118s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
NAME                                   STATUS                        ROLES    AGE    VERSION
shoot--i034796--az1-a-z1-85cf5-djz2j   Ready                         <none>   25m    v1.26.7
shoot--i034796--az1-a-z1-85cf5-m9rfx   NotReady,SchedulingDisabled   <none>   127m   v1.26.7
```

#### Poll Deployments,Pods,VolumeAttachments,Nodes at UTC Time: Thu Sep 21 09:18:49 UTC 2023, Local Time: Thu Sep 21 09:18:49 UTC 2023

```
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
deployment.apps/vol-test-a   4/4     4            4           54m   ubuntu       ubuntu   app=vol-test-a

NAME                              READY   STATUS    RESTARTS   AGE    IP           NODE                                   NOMINATED NODE   READINESS GATES
pod/vol-test-a-55bbbb77b6-dmk8n   1/1     Running   0          4m9s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-fkn7k   1/1     Running   0          4m9s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-mc52s   1/1     Running   0          4m9s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>
pod/vol-test-a-55bbbb77b6-wnnhg   1/1     Running   0          4m9s   10.180.0.6   shoot--i034796--az1-a-z1-85cf5-djz2j   <none>           <none>

NAME                                                                                                   ATTACHER             PV                                                            NODE                                   ATTACHED   AGE
volumeattachment.storage.k8s.io/csi-0779eb4f890f6377eb07997244fcbd794e9a63fc3fb0c13ea4414ac8ca67ca84   disk.csi.azure.com   pv-shoot--i034796--az1-040457ee-eaac-4b01-b690-92a814a91788   shoot--i034796--az1-a-z1-85cf5-djz2j   true       111s
volumeattachment.storage.k8s.io/csi-07f618ac82174b622379ae088200d2390615e7005fb2fbf589f2a8cdbea9f45b   disk.csi.azure.com   pv-shoot--i034796--az1-fcae9b4f-28b1-4483-aaf0-00a71f368b32   shoot--i034796--az1-a-z1-85cf5-djz2j   true       111s
volumeattachment.storage.k8s.io/csi-9e2659a49d9a40e9f5d7b1d2378e52e54739464c4c266a1b82e973d9c0983bb7   disk.csi.azure.com   pv-shoot--i034796--az1-dba037bb-eb4b-45c0-85bf-87e19b8977c0   shoot--i034796--az1-a-z1-85cf5-djz2j   true       111s
volumeattachment.storage.k8s.io/csi-c59e72b600d9a63c5a5a702a05cd3be93b0de263c782e199f255439d52def5ac   disk.csi.azure.com   pv-shoot--i034796--az1-4f4b7484-3029-4603-8806-dcaad8c1da2b   shoot--i034796--az1-a-z1-85cf5-djz2j   true       111s
NAME                                   STATUS   ROLES    AGE   VERSION
shoot--i034796--az1-a-z1-85cf5-74rpz   Ready    <none>   44s   v1.26.7
shoot--i034796--az1-a-z1-85cf5-djz2j   Ready    <none>   27m   v1.26.7
```
Pods on new node come up in ~12 mins. There is no `maxWaitForUnmountDuration` in the kube controller log.

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 1]
```diff
@@ -1018,16 +1020,17 @@ func (c *controller) drainNode(ctx context.Context, deleteMachineRequest *driver
 			}
 		}
 
+		klog.V(3).Infof("(drainNode) nodeReadyCondition: %s, readOnlyFileSystemCondition: %s", nodeReadyCondition, readOnlyFileSystemCondition)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1023]: could you also mention machine name

Comment (himanshu-kun) [reply pkg/util/provider/machinecontroller/machine_util.go:1023]: same for any other such log added

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 2]
```diff
@@ -1106,21 +1109,27 @@ func (c *controller) drainNode(ctx context.Context, deleteMachineRequest *driver
...
 			)
+			klog.V(3).Infof("(drainNode) Invoking RunDrain, forceDeleteMachine: %t, forceDeletePods: %t, timeOutDuration: %s", forceDeletePods, forceDeleteMachine, timeOutDuration)
 			err = drainOptions.RunDrain(ctx)
 			if err == nil {
 				// Drain successful
 				klog.V(2).Infof("Drain successful for machine %q ,providerID %q, backing node %q. \nBuf:%v \nErrBuf:%v", machine.Name, getProviderID(machine), getNodeName(machine), buf, errBuf)
 
-				description = fmt.Sprintf("Drain successful. %s", machineutils.InitiateVMDeletion)
+				if forceDeletePods {
+					description = fmt.Sprintf("Drain successful. %s", machineutils.DelVolumesAttachments)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1119]:
```suggestion
					description = fmt.Sprintf("Force Drain successful. %s", machineutils.DelVolumesAttachments)
```

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 3]
```diff
@@ -1106,21 +1109,27 @@ func (c *controller) drainNode(ctx context.Context, deleteMachineRequest *driver
...
+					err = fmt.Errorf(description)
+				} else { // regular drain already waits for vol detach and attach for another node.
+					description = fmt.Sprintf("Drain successful. %s", machineutils.InitiateVMDeletion)
+					err = fmt.Errorf("Machine deletion in process. " + description)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1123]: lets delete `L1120` and move this err initialization out of else block , this can stay common for both force and graceful drain situations

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 4]
```diff
@@ -1150,6 +1159,66 @@ func (c *controller) drainNode(ctx context.Context, deleteMachineRequest *driver
...
+		retryPeriod = 0
+	} else if len(node.Status.VolumesAttached) == 0 {
+		description = fmt.Sprintf("Node Volumes for node: %s are already detached. Moving to VM Deletion. %s", nodeName, machineutils.InitiateVMDeletion)
+		state = v1alpha1.MachineStateProcessing
+		retryPeriod = 0
+	} else {
+		// case: where node.Status.VolumesAttached > 0
+		liveNodeVolAttachments, err := getLiveVolumeAttachmentsForNode(c.volumeAttachementLister, nodeName)
+		if err != nil {
+			klog.Errorf("(deleteNodeVolAttachments) Error obtaining VolumeAttachment(s) for node %q: ", nodeName, err)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1189]: better to print both node name and machine name, as they are different for some cloudproviders... helps in debugging

Comment (himanshu-kun) [reply pkg/util/provider/machinecontroller/machine_util.go:1189]: pls make the change for similar other logs

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 5]
```diff
@@ -1150,6 +1159,66 @@ func (c *controller) drainNode(ctx context.Context, deleteMachineRequest *driver
...
+			description = fmt.Sprintf("No Live VolumeAttachments for node: %s. Moving to VM Deletion. %s", nodeName, machineutils.InitiateVMDeletion)
+			state = v1alpha1.MachineStateProcessing
+		} else {
+			err = deleteVolumeAttachmentsForNode(ctx, c.targetCoreClient.StorageV1().VolumeAttachments(), nodeName, liveNodeVolAttachments)
+			if err != nil {
+				klog.Errorf("(deleteNodeVolAttachments) Error deleting volume attachments for node %q: %s", nodeName, err)
+			} else {
+				klog.V(3).Infof("(deleteNodeVolAttachments) Successfully deleted all volume attachments for node %q", nodeName)
+			}
+			return retryPeriod, nil
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1202]: I have tried to delete volumeattachment for a pod which is running... I observed that the volumeattachment get re-created...
if this is the case, then we can get stuck in this cycle of trying to delete volumeattachment...could you verify it from your end

File: pkg/util/provider/machinecontroller/machine_util.go [hunk 6]
```diff
@@ -1508,6 +1577,34 @@ func (c *controller) tryMarkingMachineFailed(ctx context.Context, machine, clone
 	return machineutils.ShortRetry, err
 }
 
+func getLiveVolumeAttachmentsForNode(volAttachLister storagelisters.VolumeAttachmentLister, nodeName string) ([]*storagev1.VolumeAttachment, error) {
+	volAttachments, err := volAttachLister.List(labels.NewSelector())
+	if err != nil {
+		return nil, fmt.Errorf("cant list volume attachments for node %q: %w", nodeName, err)
```
Comment (himanshu-kun) [inline pkg/util/provider/machinecontroller/machine_util.go:1583]: also log machine name pls
```suggestion
		return nil, fmt.Errorf("can't list volume attachments for node %q: %w", nodeName, err)
```

File: docs/FAQ.md [hunk 7]
```diff
@@ -256,6 +257,24 @@ During update for scaling event, a machineSet is updated if any of the below is
...
+`Failed` machines have their deletion timestamp set and the machine then moves to the `Terminating` phase. The node
+drain process is initiated. The drain process is invoked either *gracefully* or *forcefully*.
+
+The usual drain process is graceful. Pods are evicted from the node and the drain process waits until any existing
+attached volumes are mounted on new node. However, if the node `Ready` is `False` or the `ReadonlyFilesystem` is `True`
+for greater than `5` minutes, then a forceful drain is initiated. In a forceful drain, pods are deleted
+and `VolumeAttachment` objects associated with the old node are also deleted. This is followed by the deletion of the
+cloud provider VM associated with the `Machine` and then finally ending with the `Node` object deletion. 
+
+During the deletion of the VM we only delete the local data and boot disks associated with the VM. The disks associated
```
Comment (himanshu-kun) [inline docs/FAQ.md:274]:
```suggestion
During the deletion of the VM we only delete the local data disks and boot disks associated with the VM. The disks associated
```

File: docs/FAQ.md [hunk 8]
```diff
@@ -256,6 +257,24 @@ During update for scaling event, a machineSet is updated if any of the below is
...
+
+If a node is unhealthy for more than the `machine-health-timeout` specified for the `machine-controller`, the controller
+health-check moves the machine phase to `Failed`. By default, the `machine-health-timeout` is 10` minutes.
+
+`Failed` machines have their deletion timestamp set and the machine then moves to the `Terminating` phase. The node
+drain process is initiated. The drain process is invoked either *gracefully* or *forcefully*.
+
+The usual drain process is graceful. Pods are evicted from the node and the drain process waits until any existing
+attached volumes are mounted on new node. However, if the node `Ready` is `False` or the `ReadonlyFilesystem` is `True`
+for greater than `5` minutes, then a forceful drain is initiated. In a forceful drain, pods are deleted
```
Comment (himanshu-kun) [inline docs/FAQ.md:270]:
```suggestion
for greater than `5` minutes(non-configurable), then a forceful drain is initiated. In a forceful drain, pods are deleted
```

File: docs/FAQ.md [hunk 9]
```diff
@@ -256,6 +257,24 @@ During update for scaling event, a machineSet is updated if any of the below is
...
+and `VolumeAttachment` objects associated with the old node are also deleted. This is followed by the deletion of the
```
Comment (himanshu-kun) [inline docs/FAQ.md:271]:
```suggestion
and `VolumeAttachment` objects associated with the old node are also marked for deletion. This is followed by the deletion of the
```

**Review by himanshu-kun — CHANGES_REQUESTED** [review]

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 1 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: Changed to
```go
klog.V(3).Infof("(drainNode) For node %q, machine %q, nodeReadyCondition: %s, readOnlyFileSystemCondition: %s", nodeName, machine.Name, nodeReadyCondition, readOnlyFileSystemCondition)
```

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 2 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: Distinguished the description

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 3 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: Used common `err` init for both branches to simply after the branches

```go
err = fmt.Errorf(description)
```

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 4 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: Added `machine.Name` in addition to the node name for all `klogs` in `deleteNodeVolAttachments`

```go

klog.Errorf("(deleteNodeVolAttachments) Error obtaining VolumeAttachment(s) for node %q, machine %q: %s", nodeName, machine.Name, err)
//...
klog.Errorf("(deleteNodeVolAttachments) Error deleting volume attachments for node %q, machine %q: %s", nodeName, machine.Name, err)
//...
klog.V(3).Infof("(deleteNodeVolAttachments) Successfully deleted all volume attachments for node %q, machine %q", nodeName, machine.Name)
//...
klog.Errorf("(deleteNodeVolAttachments) Error deleting volume attachments for node %q, machine %q: %s", nodeName, machine.Name, err)
//...
klog.V(3).Infof("(deleteNodeVolAttachments) Successfully deleted all volume attachments for node %q, machine %q", nodeName, machine.Name)
//...
klog.V(4).Infof("(deleteVolumeAttachmentsForNode) For node %q, machine %q, set LastOperation.Description: %q", nodeName, machine.Name, description)

````

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 5 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go:1201]: Did not follow. will call.

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 6 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go]: Changed to

```go

func getLiveVolumeAttachmentsForNode(volAttachLister storagelisters.VolumeAttachmentLister, nodeName string, machineName string) ([]*storagev1.VolumeAttachment, error) {
	volAttachments, err := volAttachLister.List(labels.NewSelector())
	if err != nil {
		return nil, fmt.Errorf("cant list volume attachments for node %q, machine %q: %w", nodeName, machineName, err)
	}
	//...
}
```

**Comment by elankath** [comment]
## Additional Test Requested

Attempt to skip the drain and move directly to deletion of node volumes.

### Test Steps
1. Introduced code for testing in `controller.drainNode` to skip drain and simulate error.
```go
			if false { // SKIPPED OUT TO CHECK BEHAVIOUR IF POD DEL DIDN't OCCUR
				err = drainOptions.RunDrain(ctx) 
			}
			err = fmt.Errorf("PRETEND DRAIN RAN INTO ERR")

```
2. Now crash the node kubelet and check behaviour. New machine should be launched and Pod's should be moved to new node.

File: pkg/util/provider/machinecontroller/machine_util.go (hunk 5 above)
Comment (elankath) [reply pkg/util/provider/machinecontroller/machine_util.go:1201]: test done

File: docs/FAQ.md (hunk 7 above)
Comment (elankath) [reply docs/FAQ.md]: done

File: docs/FAQ.md (hunk 8 above)
Comment (elankath) [reply docs/FAQ.md]: done

File: docs/FAQ.md (hunk 9 above)
Comment (elankath) [reply docs/FAQ.md]: done

**Review by himanshu-kun — APPROVED** [review]
/lgtm
