### PR TITLE
Fixing handling of global timout for node drain

### LINKED ISSUE #269: How is globalTimeout handled when draining a node
When draining a node, `evictPods()` is called. It is supposed to wait for duration `globalTimeout` for evicting all the pods.
https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/drain.go#L367
If each of the pods take different times to be evicted, then the timeout timer starts again from 0 because of `for`-ever loop.

### PR DESCRIPTION
**Pull request by ggaurav10**
**What this PR does / why we need it**:
Global timeout for drain restarts after each successful/unsuccessful pod eviction. This PR fixes this issue.

**Which issue(s) this PR fixes**:
Fixes #269 

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

File: pkg/controller/drain.go [hunk 1]
```diff
@@ -313,13 +314,12 @@ func (o *DrainOptions) deleteOrEvictPods(pods []api.Pod) error {
 }
 
 func (o *DrainOptions) evictPods(pods []api.Pod, policyGroupVersion string, getPodFn func(namespace, name string) (*api.Pod, error)) error {
-	doneCh := make(chan bool, len(pods))
-	errCh := make(chan error, 1)
+	returnCh := make(chan error, 1)
```
Comment (hardikdr) [inline pkg/controller/drain.go]: Should the buffered channel be initialized to len(pods) , as there could be more elements in it?

File: pkg/controller/drain.go [hunk 2]
```diff
@@ -328,46 +328,49 @@ func (o *DrainOptions) evictPods(pods []api.Pod, policyGroupVersion string, getP
...
 	}
-	for {
+	globalTimeoutCh := time.After(globalTimeout)
+	numPods := len(pods)
+	for doneCount < numPods {
 		select {
-		case err := <-errCh:
-			return err
-		case <-doneCh:
+		case err := <-returnCh:
```
Comment (hardikdr) [inline pkg/controller/drain.go]: Will the error while evicting the pod is considered as doneCount++? This is intentional right? 
I am not sure of the best behavior here, as the pod then will anyways be not processed later, so we can keep it this way.

File: pkg/controller/drain.go (hunk 1 above)
Comment (ggaurav10) [reply pkg/controller/drain.go]: This logic is taken from:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain/drain.go#L354

I guess we would end up serialising the "exiting of Go routines" also, instead of serialising just the "incrementing `doneCount`".

File: pkg/controller/drain.go (hunk 2 above)
Comment (ggaurav10) [reply pkg/controller/drain.go]: Yes, error is considered for the increment. Taken from here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain/drain.go#L397

Open to better options. The errors are just logged, and basically noop.

File: pkg/controller/drain.go (hunk 1 above)
Comment (hardikdr) [reply pkg/controller/drain.go]: I see. Not sure, at the lowest level how golang would behave, but I understand if by any chance more than one elements are piped into the channel, it would panic. 
Let's keep it this way then.

File: pkg/controller/drain.go (hunk 2 above)
Comment (hardikdr) [reply pkg/controller/drain.go]: Okay, I think then makes sense to count error'ed eviction as done.
